"""Health checks. Exit 0 when everything passes; exit 1 with the list of
failed checks otherwise (wiring in cli.py).

Checks (per spec): DB exists · required folders exist · Obsidian Home.md
exists · every done task has evidence unless an override event exists ·
generated wikilinks point to existing generated notes · nothing outside
AOS/ was generated by sync.
"""

from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from . import ids, obsidian, utils

_WIKILINK = re.compile(r"\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]")

_NOTE_PATTERNS = {
    "Tasks": re.compile(r"^T-[0-9]{4,}$"),
    "Runs": re.compile(r"^R-[0-9]{4,}$"),
    "Decisions": re.compile(r"^D-[0-9]{4,}$"),
    "Evidence": re.compile(r"^E-[0-9]{4,}$"),
    "Handoffs": re.compile(r"^H-[0-9]{4,}$"),
    "Projects": re.compile(r"^[a-z0-9][a-z0-9._-]*$", re.ASCII),
}


@dataclass
class Check:
    name: str
    ok: bool
    detail: str = ""


def _is_hidden(path: Path, base: Path) -> bool:
    """True when any component below `base` starts with '.' (e.g. the
    .obsidian folder Obsidian creates at the vault root)."""
    return any(
        part.startswith(".") for part in path.relative_to(base).parts
    )


def run_checks(conn: sqlite3.Connection, aos_dir: Path) -> list[Check]:
    checks: list[Check] = []
    aos_root = obsidian.vault_aos_dir(aos_dir)

    # 1. DB exists.
    db_path = aos_dir / utils.DB_FILENAME
    checks.append(Check("database exists", db_path.is_file(), str(db_path)))

    # 2. Required folders exist.
    required = [aos_dir / name for name in obsidian.WORKSPACE_DIRS]
    required.append(aos_root)
    required += [aos_root / name for name in obsidian.ENTITY_DIRS]
    missing = [str(p) for p in required if not p.is_dir()]
    checks.append(
        Check(
            "required folders exist",
            not missing,
            "; ".join(f"missing {m}" for m in missing),
        )
    )

    # 3. Obsidian Home.md exists.
    home = aos_root / "Home.md"
    checks.append(Check("Home.md exists", home.is_file(), str(home)))

    # 4. Every done task has evidence unless an override event exists.
    offenders = []
    for row in conn.execute(
        "SELECT t.id FROM tasks t WHERE t.status = 'done' "
        "AND NOT EXISTS (SELECT 1 FROM evidence e WHERE e.task_id = t.id) "
        "AND NOT EXISTS (SELECT 1 FROM events ev WHERE ev.entity = 'task' "
        "AND ev.entity_id = t.id AND ev.action = 'done_override') "
        "ORDER BY t.id"
    ).fetchall():
        offenders.append(ids.render_id("task", row["id"]))
    checks.append(
        Check(
            "done tasks have evidence (or a logged override)",
            not offenders,
            "no evidence and no override event: " + ", ".join(offenders)
            if offenders
            else "",
        )
    )

    # 5. Generated wikilinks resolve to existing generated notes.
    broken = []
    if aos_root.is_dir():
        stems = {
            path.stem
            for path in aos_root.rglob("*.md")
            if not _is_hidden(path, aos_root)
        }
        for path in sorted(aos_root.rglob("*.md")):
            if _is_hidden(path, aos_root):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                broken.append(
                    f"{path.relative_to(aos_root).as_posix()}: not valid UTF-8"
                )
                continue
            for match in _WIKILINK.finditer(text):
                target = match.group(1).strip()
                if target not in stems:
                    broken.append(
                        f"{path.relative_to(aos_root).as_posix()} → [[{target}]]"
                    )
    checks.append(
        Check(
            "wikilinks resolve to generated notes",
            not broken,
            "; ".join(broken[:10]),
        )
    )

    # 6. Nothing outside AOS/ was generated by sync, and everything inside
    #    AOS/ is a recognized generated note. (Hidden entries such as
    #    Obsidian's own .obsidian/ folder are the user's, not sync's.)
    strays = []
    vault = aos_dir / obsidian.VAULT_DIRNAME
    if vault.is_dir():
        for path in sorted(vault.rglob("*")):
            if not path.is_file() or _is_hidden(path, vault):
                continue
            if aos_root not in path.parents:
                strays.append(path.relative_to(vault).as_posix())
                continue
            rel = path.relative_to(aos_root)
            if rel.as_posix() in ("Home.md", "CONVENTIONS.md"):
                continue
            pattern = (
                _NOTE_PATTERNS.get(rel.parts[0]) if len(rel.parts) == 2 else None
            )
            if (
                pattern is None
                or path.suffix != ".md"
                or not pattern.match(path.stem)
            ):
                strays.append(rel.as_posix())
    checks.append(
        Check(
            "mirror contains only generated AOS/ notes",
            not strays,
            "; ".join(strays[:10]),
        )
    )

    return checks
