"""Health checks. Exit 0 when everything passes; exit 1 with the list of
failed checks otherwise (wiring in cli.py).

Night-1 checks: DB exists · required folders exist · Obsidian Home.md
exists · every done task has evidence unless an override event exists ·
generated wikilinks point to existing generated notes · nothing outside
AOS/ was generated by sync.

Weekend hardening adds: schema_version supported · task statuses inside the
vocabulary · handoffs reference existing tasks · task-linked decisions
reference existing tasks · memory supersede pointers resolve · packs
reference existing tasks and their files exist on disk.

Complete-today hardening adds: agent registry rows well-formed · dropfile
ingest events carry their dedupe hash · generated entity notes have
well-formed frontmatter · PRAGMA integrity_check — plus one WARN-ONLY line
(code tasks done without commit evidence) that never fails the run.

U-C3 adds one more WARN-ONLY line: a bounded secret sweep over the
canonical ledger rows and event payloads, naming identifiers plus
field/pattern names only — never a stored value. Event payloads are
covered twice: the safe secret_warning/secret_fields/secret_patterns
metadata (redacted post-U-C3 events carry nothing else) and a raw scan of
legacy payload strings via the shared detector. The events.actor column
is raw-scanned too (fixed label `actor`) for legacy pre-redaction rows.

U-H2 adds two more WARN-ONLY lines: ended success runs with no acceptable
evidence attributable inside the run-bounded recovery window
(D-v0.2.37), and legacy evidence rows whose ref is blank after
normalization (D-v0.2.36) — both name bounded run/evidence IDs and counts
only, never a ref, claim, summary, or agent value.

U-M2 adds four memory-claim lines (checks 22-25): claim shape and hash
integrity, evidence-link resolution (both FAIL), plus two WARN-ONLY facts —
pinned-but-ineligible claims, and non-retired claims past their valid_until.
Same rule as every line above: M-XXXX/E-XXXX ids, closed-vocabulary status
names and counts only. Never a key, value, source, evidence ref, or a hash.

U-M3 adds five memory-graph lines (checks 26-30): sensitivity vocabulary,
source shape/target/window/hash, source-link resolution plus project and
sensitivity compatibility, edge shape/canonical-form/scope/hash (all FAIL),
and one WARN-ONLY fact — restricted claim text found in a generated pack or
mirror note, which a `pack build` predating the classification reaches
honestly. Same rule again: ids, reason codes, generated file names and counts.
Never a key, value, locator, provenance, evidence ref, or a hash.

U-A1 rewrites check 13 for the governed v4 identity shape and adds three
agent-registry lines (checks 32-34): identity hashes verify, passport
history intact (both FAIL — and both feed the recovery gate, so a tampered
registry blocks leaving recovery), plus one WARN-ONLY fact — active agents
with no published passport, which every migrated legacy agent honestly is.
The secret sweep extends over stored passport documents. Same rule as every
line above: name-or-`agent #id`, `v<N>`, closed verdicts and counts only.
Never a role, mission, note, document excerpt, or a hash value.

U-A2 adds three built-in-catalog lines (checks 35-37): the shipped catalog
verifies as a whole (FAIL), every installed catalog identity is coherent
with it (FAIL), and any actionable upgrade or name collision is surfaced
(WARN-ONLY — never firing merely because the catalog was never installed).
All three reuse `catalog.verify()`/`catalog.status()` rather than reading
`agents`/`agent_passports` directly, and reduce every problem to a bounded
count plus closed reason codes drawn from `catalog._REASON_HINTS` — never
the message text itself, an artifact value, a path, or a full hash. Doctor
never installs, upgrades, or otherwise mutates the catalog.
"""

from __future__ import annotations

import json
import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from . import db, ids, models, obsidian, ops, power, secretscan, utils
from .models import (
    AGENT_CLASSES,
    AGENT_KINDS,
    AGENT_LIFECYCLES,
    AGENT_NAME_RE,
    AGENT_ORIGINS,
    AGENT_OWNERS,
    AGENT_SCOPES,
    MAX_AGENT_NAME_CHARS,
    MEMORY_SENSITIVITY_RESTRICTED,
    MEMORY_STATUS_RETIRED,
    MEMORY_STATUSES,
    TASK_STATUSES,
    Agent,
    MemoryItem,
)
from .utils import AosError

# Shared generated-layout rules live in obsidian.py (public, also consumed
# by the U-C4 mirror export); these aliases keep doctor's historical names.
_WIKILINK = obsidian.WIKILINK_RE
_NOTE_PATTERNS = obsidian.NOTE_STEM_PATTERNS


@dataclass
class Check:
    name: str
    ok: bool
    detail: str = ""
    #: A warn-only check prints [WARN] instead of [FAIL] and never affects
    #: the exit code.
    warn_only: bool = False


#: Secret-sweep findings shown per doctor run; the rest is a count. Keeps
#: large ledgers from producing unbounded terminal output (U-C3.5).
SECRET_SWEEP_DISPLAY_LIMIT = 10

#: Offender IDs shown per U-H2 warn line (checks 19/20); the rest is a count.
UH2_DISPLAY_LIMIT = 10

#: The concise degradation summary per mode for check 21 (U-E2). Fixed
#: strings: the full matrix lives in `power status`, not in every doctor run.
_POWER_SUMMARY = {
    power.ECO: "implicit derived refresh deferred",
    power.STANDARD: "baseline behavior",
    power.DEEP: "integrity + secret preflight around authoritative writes",
    power.RECOVERY: "authoritative writes blocked",
}


def _bounded_ids(offenders: list[str], noun: str) -> str:
    """Total count plus at most the first UH2_DISPLAY_LIMIT rendered IDs —
    output derived from ledger rows stays bounded, and only IDs are ever
    shown, never a stored value."""
    if not offenders:
        return ""
    detail = (
        f"{len(offenders)} {noun}(s): "
        + ", ".join(offenders[:UH2_DISPLAY_LIMIT])
    )
    extra = len(offenders) - UH2_DISPLAY_LIMIT
    if extra > 0:
        detail += f" (+{extra} more)"
    return detail

#: (entity, table, (field label, column)) — the canonical human-text
#: fields the U-C3 sweep scans; the entity name is also the render_id key.
_SWEEP_DOMAIN_FIELDS = (
    ("task", "tasks", (
        ("title", "title"),
        ("spec", "spec_md"),
        ("acceptance", "acceptance_md"),
        # No CLI write path yet, but rendered into task frontmatter and
        # pack REPO & BRANCH content — mirror/pack-bearing, so swept.
        ("assignee", "assignee"),
        ("branch_hint", "branch_hint"),
    )),
    ("run", "runs", (
        ("agent", "agent"),
        ("summary", "summary_md"),
    )),
    ("decision", "decisions", (
        ("title", "title"),
        ("decision", "decision_md"),
        ("alternatives", "alternatives_md"),
    )),
    ("evidence", "evidence", (
        ("ref", "ref"),
        ("claim", "claim"),
        # Trusted mirror/export-bearing field: the canonical row keeps a
        # warned credential-shaped provenance, so the sweep must find it.
        ("provenance", "provenance"),
    )),
    ("handoff", "handoffs", (
        ("from_agent", "from_agent"),
        ("to_agent", "to_agent"),
        ("state", "state_md"),
    )),
    ("memory", "memory", (
        ("key", "key"),
        ("value", "value_md"),
        ("source", "source"),
    )),
    # U-M3 sources. A locator is a path, URL or command string the operator
    # typed — the exact shape that carries a token in a query string — and the
    # warn-on-write path already flags one at the CLI boundary. This is the
    # half that finds the ones written directly, or written before the
    # detector knew the pattern. The value is never echoed: the finding is
    # MS-XXXX plus the field and pattern NAMES, like every line above.
    ("memory_source", "memory_sources", (
        ("locator", "locator"),
        ("provenance", "provenance"),
    )),
)


def _iter_payload_strings(value, key: str | None = None):
    """Yield (innermost key, string value) pairs from a decoded event
    payload. Strings are scanned individually so a JSON key like "key"
    or "token_estimate" can never lend keyword context to a neighboring
    value."""
    if isinstance(value, str):
        yield key or "payload", value
    elif isinstance(value, dict):
        for child_key, child in value.items():
            yield from _iter_payload_strings(child, child_key)
    elif isinstance(value, list):
        for child in value:
            yield from _iter_payload_strings(child, key)


#: A payload key doctor is willing to echo as a finding label: one of our
#: snake_case identifiers, nothing longer or stranger. Keys are stored
#: data too — a tampered event must not smuggle text out through the label.
_PAYLOAD_KEY_RE = re.compile(r"^[a-z][a-z0-9_]{0,31}\Z", re.ASCII)


def _safe_payload_key(key: str) -> str:
    if _PAYLOAD_KEY_RE.match(key) and not secretscan.scan_secrets(key):
        return key
    return "payload"


def _event_secret_metadata(payload) -> list[tuple[str, list[str]]]:
    """Read well-formed U-C3 event metadata (D-v0.2.21): the safe record a
    redacted post-U-C3 event keeps of what its payload no longer shows.
    Returns [(field, pattern names)] with every name validated against the
    fixed allowlists — secretscan.TRUSTED_FIELD_LABELS and
    secretscan.PATTERN_NAMES — so malformed or tampered metadata is
    ignored, never echoed. (Its strings still get the raw leaf scan.)"""
    if not isinstance(payload, dict) or payload.get("secret_warning") is not True:
        return []
    fields = payload.get("secret_fields")
    patterns = payload.get("secret_patterns")
    if not isinstance(fields, list) or not isinstance(patterns, list):
        return []
    safe_fields = list(
        dict.fromkeys(
            field
            for field in fields
            if isinstance(field, str)
            and field in secretscan.TRUSTED_FIELD_LABELS
        )
    )
    safe_patterns = [
        name for name in secretscan.PATTERN_NAMES if name in patterns
    ]
    if not safe_fields or not safe_patterns:
        return []
    return [(field, safe_patterns) for field in safe_fields]


def _secret_sweep_findings(conn: sqlite3.Connection) -> list[str]:
    """U-C3.5 ledger sweep: every finding names an entity type, a public
    ID (or event #id), the field, and the pattern names — never a stored
    value, excerpt, or fingerprint. Domain rows get the raw scan; events
    get the safe-metadata read plus the raw scan of legacy payloads and
    of the top-level actor column (legacy raw actors)."""
    findings: list[str] = []

    def note(label: str, fields) -> None:
        # Hand the detector text and nothing else. A TEXT column can hold a
        # BLOB — only reachable by editing the file outside Agentic OS — and
        # the shared regex detector takes str, so an unfiltered value would
        # crash the very report that exists to name the damage. Identity for
        # every real value; the damaged cell is reported by the check that
        # owns it (memory claims: check 22).
        text_only = [
            (field, value)
            for field, value in fields
            if value is None or isinstance(value, str)
        ]
        for field, hits in secretscan.scan_fields(text_only):
            findings.append(f"{label} {field}: {','.join(hits)}")

    # Projects and agents are identified by ROW id: their public names
    # (slug, agent name) are themselves scanned fields, and a secret-shaped
    # one must never be echoed as the identifier of another field's hit.
    for row in conn.execute(
        "SELECT id, slug, name, repo_path, conventions_md FROM projects "
        "ORDER BY id"
    ).fetchall():
        note(
            f"project #{row['id']}",
            [
                ("slug", row["slug"]),
                ("name", row["name"]),
                ("repo_path", row["repo_path"]),
                ("conventions", row["conventions_md"]),
            ],
        )
    for entity, table, columns in _SWEEP_DOMAIN_FIELDS:
        for row in conn.execute(
            f"SELECT * FROM {table} ORDER BY id"
        ).fetchall():
            hid = ids.render_id(entity, row["id"])
            note(
                f"{entity} {hid}",
                [(field, row[column]) for field, column in columns],
            )
    for row in conn.execute(
        "SELECT id, name, invoke_hint, notes, capabilities_json FROM agents "
        "ORDER BY id"
    ).fetchall():
        capabilities = None
        if row["capabilities_json"]:
            try:
                decoded = json.loads(row["capabilities_json"])
                if isinstance(decoded, list):
                    capabilities = "\n".join(
                        item for item in decoded if isinstance(item, str)
                    )
            except ValueError:
                pass  # check 13 already reports the malformed JSON
        note(
            f"agent #{row['id']}",
            [
                ("name", row["name"]),
                ("invoke_hint", row["invoke_hint"]),
                ("notes", row["notes"]),
                ("capabilities", capabilities),
            ],
        )
    # U-A1 passport documents: every string leaf, under safe keys — role,
    # mission and limitations are exactly the prose an operator pastes a
    # credential into. Identified by agent row id + version, never by name.
    for row in conn.execute(
        "SELECT agent_id, version, document FROM agent_passports "
        "ORDER BY agent_id, version"
    ).fetchall():
        document = row["document"]
        if not isinstance(document, str):
            continue  # check 33 reports the damaged document
        try:
            payload = json.loads(document)
        except ValueError:
            continue  # check 33 reports the malformed document
        note(
            f"agent #{row['agent_id']} passport v{row['version']}",
            (
                (_safe_payload_key(field), value)
                for field, value in _iter_payload_strings(payload)
            ),
        )
    for row in conn.execute(
        "SELECT id, actor, payload_json FROM events ORDER BY id"
    ).fetchall():
        label = f"event #{row['id']}"
        # Legacy raw actor values, under the FIXED label "actor" (never
        # derived from the stored text). emit now redacts a secret-shaped
        # actor to the benign placeholder, so only pre-redaction rows can
        # hit here; redacted new events surface via their safe metadata.
        note(label, [("actor", row["actor"])])
        try:
            payload = json.loads(row["payload_json"])
        except ValueError:
            continue  # check 14 reports unparseable dropfile payloads
        # Safe metadata first (the only trace a redacted event keeps),
        # then the raw leaf scan for legacy pre-redaction payloads. Keys
        # pass _safe_payload_key so no stored text rides out as a label.
        for field, patterns in _event_secret_metadata(payload):
            findings.append(f"{label} {field}: {','.join(patterns)}")
        note(
            label,
            (
                (_safe_payload_key(field), value)
                for field, value in _iter_payload_strings(payload)
            ),
        )
    # Metadata and a legacy raw payload (or repeated payload keys) can
    # produce identical finding lines; report each distinct finding once,
    # in first-seen order — deterministic for identical ledgers.
    return list(dict.fromkeys(findings))


def secret_sweep_findings(conn: sqlite3.Connection) -> list[str]:
    """Public name for the U-C3 ledger sweep.

    The U-E2 deep preflight runs the SAME sweep the doctor line runs — one
    detector, one answer to "is this secret-shaped?" everywhere (D-v0.2.15).
    Deep reports only the COUNT of these findings; `doctor` remains the place
    that shows them (already bounded, already value-free).
    """
    return _secret_sweep_findings(conn)


#: Entity folders whose notes carry frontmatter (Reviews and the top-level
#: Home/CONVENTIONS/index notes deliberately have none).
FRONTMATTER_DIRS = (
    "Projects",
    "Tasks",
    "Runs",
    "Decisions",
    "Evidence",
    "Handoffs",
    "Memory",
    "Agents",
)

_FRONTMATTER_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*:( .*)?|  - .+)$")


def _frontmatter_problem(text: str) -> str | None:
    lines = text.split("\n")
    if not lines or lines[0] != "---":
        return "missing opening '---'"
    for index in range(1, len(lines)):
        if lines[index] == "---":
            return "empty frontmatter" if index == 1 else None
        if not _FRONTMATTER_LINE.match(lines[index]):
            return f"bad frontmatter line {index + 1}"
    return "missing closing '---'"


def _is_hidden(path: Path, base: Path) -> bool:
    """Shared rule (obsidian.is_hidden_rel, D-P5.2) under doctor's
    historical name."""
    return obsidian.is_hidden_rel(path, base)


def run_checks(conn: sqlite3.Connection, aos_dir: Path) -> list[Check]:
    checks: list[Check] = []
    aos_root = obsidian.vault_aos_dir(aos_dir)

    # 1. DB exists.
    db_path = aos_dir / utils.DB_FILENAME
    checks.append(Check("database exists", db_path.is_file(), str(db_path)))

    # 2. Required folders exist.
    required = [aos_dir / name for name in obsidian.WORKSPACE_DIRS]
    required.append(aos_root)
    required += [aos_root / name for name in obsidian.ENTITY_DIRS]
    missing = [str(p) for p in required if not p.is_dir()]
    checks.append(
        Check(
            "required folders exist",
            not missing,
            "; ".join(f"missing {m}" for m in missing),
        )
    )

    # 3. Obsidian Home.md exists.
    home = aos_root / "Home.md"
    checks.append(Check("Home.md exists", home.is_file(), str(home)))

    # 4. Every done task has evidence unless an override event exists.
    offenders = []
    for row in conn.execute(
        "SELECT t.id FROM tasks t WHERE t.status = 'done' "
        "AND NOT EXISTS (SELECT 1 FROM evidence e WHERE e.task_id = t.id) "
        "AND NOT EXISTS (SELECT 1 FROM events ev WHERE ev.entity = 'task' "
        "AND ev.entity_id = t.id AND ev.action = 'done_override') "
        "ORDER BY t.id"
    ).fetchall():
        offenders.append(ids.render_id("task", row["id"]))
    checks.append(
        Check(
            "done tasks have evidence (or a logged override)",
            not offenders,
            "no evidence and no override event: " + ", ".join(offenders)
            if offenders
            else "",
        )
    )

    # 5. Generated wikilinks resolve to existing generated notes.
    broken = []
    if aos_root.is_dir():
        stems = {
            path.stem
            for path in aos_root.rglob("*.md")
            if not _is_hidden(path, aos_root)
        }
        for path in sorted(aos_root.rglob("*.md")):
            if _is_hidden(path, aos_root):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                broken.append(
                    f"{path.relative_to(aos_root).as_posix()}: not valid UTF-8"
                )
                continue
            for match in _WIKILINK.finditer(text):
                target = match.group(1).strip()
                if target not in stems:
                    broken.append(
                        f"{path.relative_to(aos_root).as_posix()} → [[{target}]]"
                    )
    checks.append(
        Check(
            "wikilinks resolve to generated notes",
            not broken,
            "; ".join(broken[:10]),
        )
    )

    # 6. Nothing outside AOS/ was generated by sync, and everything inside
    #    AOS/ is a recognized generated note. (Hidden entries such as
    #    Obsidian's own .obsidian/ folder are the user's, not sync's.)
    strays = []
    vault = aos_dir / obsidian.VAULT_DIRNAME
    if vault.is_dir():
        for path in sorted(vault.rglob("*")):
            if not path.is_file() or _is_hidden(path, vault):
                continue
            if aos_root not in path.parents:
                strays.append(path.relative_to(vault).as_posix())
                continue
            rel = path.relative_to(aos_root)
            if not obsidian.recognized_note_rel(rel):
                strays.append(rel.as_posix())
    checks.append(
        Check(
            "mirror contains only generated AOS/ notes",
            not strays,
            "; ".join(strays[:10]),
        )
    )

    # 7. schema_version supported by this build.
    version = db.get_meta(conn, "schema_version")
    checks.append(
        Check(
            "schema_version supported",
            version == db.SCHEMA_VERSION,
            ""
            if version == db.SCHEMA_VERSION
            else f"found {version!r}, this build supports {db.SCHEMA_VERSION!r}",
        )
    )

    # 8. No task carries a status outside the vocabulary.
    marks = ",".join("?" * len(TASK_STATUSES))
    bad_status = conn.execute(
        f"SELECT id, status FROM tasks WHERE status NOT IN ({marks}) "
        "ORDER BY id",
        TASK_STATUSES,
    ).fetchall()
    checks.append(
        Check(
            "task statuses inside the vocabulary",
            not bad_status,
            "; ".join(
                f"{ids.render_id('task', row['id'])}: {row['status']!r}"
                for row in bad_status[:10]
            ),
        )
    )

    # 9. Handoffs point to existing tasks.
    orphan_handoffs = conn.execute(
        "SELECT h.id FROM handoffs h LEFT JOIN tasks t ON t.id = h.task_id "
        "WHERE t.id IS NULL ORDER BY h.id"
    ).fetchall()
    checks.append(
        Check(
            "handoffs reference existing tasks",
            not orphan_handoffs,
            "; ".join(
                ids.render_id("handoff", row["id"])
                for row in orphan_handoffs[:10]
            ),
        )
    )

    # 10. Task-linked decisions point to existing tasks.
    orphan_decisions = conn.execute(
        "SELECT d.id FROM decisions d LEFT JOIN tasks t ON t.id = d.task_id "
        "WHERE d.task_id IS NOT NULL AND t.id IS NULL ORDER BY d.id"
    ).fetchall()
    checks.append(
        Check(
            "task-linked decisions reference existing tasks",
            not orphan_decisions,
            "; ".join(
                ids.render_id("decision", row["id"])
                for row in orphan_decisions[:10]
            ),
        )
    )

    # 11. Memory supersede pointers resolve to existing memory rows.
    dangling_memory = conn.execute(
        "SELECT m.id, m.superseded_by FROM memory m "
        "LEFT JOIN memory s ON s.id = m.superseded_by "
        "WHERE m.superseded_by IS NOT NULL AND s.id IS NULL ORDER BY m.id"
    ).fetchall()
    checks.append(
        Check(
            "memory supersede pointers resolve",
            not dangling_memory,
            "; ".join(
                f"{ids.render_id('memory', row['id'])} → missing "
                f"{ids.render_id('memory', row['superseded_by'])}"
                for row in dangling_memory[:10]
            ),
        )
    )

    # 12. Packs reference existing tasks and their files exist on disk.
    pack_problems = []
    for row in conn.execute(
        "SELECT p.id, p.path, t.id AS task_ref FROM packs p "
        "LEFT JOIN tasks t ON t.id = p.task_id ORDER BY p.id"
    ).fetchall():
        pack_hid = ids.render_id("pack", row["id"])
        if row["task_ref"] is None:
            pack_problems.append(f"{pack_hid} → missing task")
        elif not (aos_dir / row["path"]).is_file():
            pack_problems.append(f"{pack_hid} → missing file {row['path']}")
    checks.append(
        Check(
            "packs reference existing tasks and files",
            not pack_problems,
            "; ".join(pack_problems[:10]),
        )
    )

    # 13. Agent identity rows are well-formed (U-A1: the v4 governed shape —
    #     vocabularies, scope↔project consistency, resolvable project — plus
    #     the v3 legacy-history rules this check has always enforced: name
    #     charset, kind vocabulary when a kind is carried, capabilities_json
    #     a JSON array when carried). Historical violations are REPORTED,
    #     never rewritten.
    bad_agents = []
    project_ids = {
        r["id"] for r in conn.execute("SELECT id FROM projects").fetchall()
    }
    for row in conn.execute("SELECT * FROM agents ORDER BY id").fetchall():
        problems = []
        name = row["name"] or ""
        valid_name = isinstance(name, str) and bool(AGENT_NAME_RE.match(name))
        # The identifier doctor echoes: the name when it is well-formed and
        # not secret-shaped, the row id otherwise (a name is itself a
        # scanned field and must never ride out as another finding's label).
        label = (
            name
            if valid_name and not secretscan.scan_secrets(name)
            else f"agent #{row['id']}"
        )
        if not valid_name:
            problems.append("invalid name")
        elif row["origin"] != "legacy" and len(name) > MAX_AGENT_NAME_CHARS:
            # Legacy names are carried verbatim whatever their length; only
            # the governed populations own the new-name bound.
            problems.append("name exceeds the new-name bound")
        if row["agent_class"] not in AGENT_CLASSES:
            problems.append("unknown agent class")
        if row["scope"] not in AGENT_SCOPES:
            problems.append("unknown scope")
        if row["lifecycle"] not in AGENT_LIFECYCLES:
            problems.append("unknown lifecycle")
        if row["owner"] not in AGENT_OWNERS:
            problems.append("unknown owner")
        if row["origin"] not in AGENT_ORIGINS:
            problems.append("unknown origin")
        if row["scope"] == "project":
            if row["project_id"] is None:
                problems.append("project scope without a project")
            elif row["project_id"] not in project_ids:
                problems.append("project does not resolve")
        elif row["project_id"] is not None:
            problems.append("global scope with a project")
        if row["kind"] is not None and row["kind"] not in AGENT_KINDS:
            problems.append("unknown kind")
        if row["capabilities_json"] is not None:
            try:
                value = json.loads(row["capabilities_json"])
                if not isinstance(value, list):
                    problems.append("capabilities_json is not a JSON array")
            except (TypeError, ValueError):
                problems.append("capabilities_json does not parse")
        if problems:
            bad_agents.append(f"{label}: " + ", ".join(problems))
    checks.append(
        Check(
            "agent registry rows are well-formed",
            not bad_agents,
            "; ".join(bad_agents[:10]),
        )
    )

    # 14. Duplicate-dropfile protection intact: every ingest event carries
    #     the sha256 the dedupe scan relies on.
    bad_ingests = []
    for row in conn.execute(
        "SELECT id, payload_json FROM events "
        "WHERE entity = 'system' AND action = 'dropfile_ingest' ORDER BY id"
    ).fetchall():
        try:
            payload = json.loads(row["payload_json"])
        except ValueError:
            bad_ingests.append(f"event #{row['id']}: payload does not parse")
            continue
        sha = payload.get("sha256")
        if not isinstance(sha, str) or len(sha) != 64:
            bad_ingests.append(f"event #{row['id']}: missing sha256")
    checks.append(
        Check(
            "dropfile ingest events carry their dedupe hash",
            not bad_ingests,
            "; ".join(bad_ingests[:10]),
        )
    )

    # 15. Generated entity notes have well-formed frontmatter.
    bad_frontmatter = []
    for dirname in FRONTMATTER_DIRS:
        folder = aos_root / dirname
        if not folder.is_dir():
            continue
        for path in sorted(folder.glob("*.md")):
            if _is_hidden(path, aos_root):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue  # check 5 already reports the encoding failure
            problem = _frontmatter_problem(text)
            if problem:
                bad_frontmatter.append(f"{dirname}/{path.name}: {problem}")
    checks.append(
        Check(
            "generated notes have well-formed frontmatter",
            not bad_frontmatter,
            "; ".join(bad_frontmatter[:10]),
        )
    )

    # 16. SQLite structural integrity.
    try:
        integrity = conn.execute("PRAGMA integrity_check").fetchone()[0]
    except sqlite3.DatabaseError as exc:
        integrity = f"error: {exc}"
    checks.append(
        Check(
            "database integrity_check passes",
            integrity == "ok",
            "" if integrity == "ok" else str(integrity)[:200],
        )
    )

    # 17 (WARN, never fatal). Code tasks closed without commit evidence —
    #     surfaced here and in the review's matching section.
    warn_offenders = [
        ids.render_id("task", row["id"])
        for row in conn.execute(
            "SELECT id FROM tasks WHERE status = 'done' AND kind = 'code' "
            "AND NOT EXISTS (SELECT 1 FROM evidence e "
            "WHERE e.task_id = tasks.id AND e.kind = 'commit') ORDER BY id"
        ).fetchall()
    ]
    checks.append(
        Check(
            "code tasks done without commit evidence",
            not warn_offenders,
            ", ".join(warn_offenders[:10]),
            warn_only=True,
        )
    )

    # 18 (WARN, never fatal). U-C3 secret sweep (D-v0.2.15): secret-shaped
    #     text sitting in otherwise valid ledger rows, or event payloads
    #     whose safe metadata (or legacy raw strings) mark one. The ledger
    #     stays an honest historical record — doctor names the affected
    #     identifiers, field and pattern names so the human can
    #     rotate/remove, and never prints a stored value. Output is bounded.
    secret_findings = _secret_sweep_findings(conn)
    shown = secret_findings[:SECRET_SWEEP_DISPLAY_LIMIT]
    hidden = len(secret_findings) - len(shown)
    detail = "; ".join(shown)
    if hidden > 0:
        detail += f" (+{hidden} more)"
    checks.append(
        Check(
            "secret-shaped text in ledger rows or event payloads",
            not secret_findings,
            detail,
            warn_only=True,
        )
    )

    # 19 (WARN, never fatal). U-H2 (D-v0.2.37): ended runs claiming
    #     outcome 'success' with no acceptable evidence attributable to
    #     them. Attribution is the run-bounded recovery window: same task,
    #     non-blank ref (Python whitespace semantics), created_at >= the
    #     run's started_at, and — when a later run exists for the task,
    #     ordered by (started_at, id) — created_at strictly before that
    #     next run's started_at. The strict bound makes the shared-second
    #     boundary conservative: evidence at the shared timestamp never
    #     heals the earlier run once the later one exists. evidence.run_id
    #     is deliberately not consulted or populated. The detail names run
    #     IDs and counts only — never a ref, claim, summary, or agent.
    unproven_runs: list[str] = []
    for run_row in conn.execute(
        "SELECT id, task_id, started_at FROM runs "
        "WHERE ended_at IS NOT NULL AND outcome = 'success' ORDER BY id"
    ).fetchall():
        next_row = conn.execute(
            "SELECT started_at FROM runs WHERE task_id = ? "
            "AND (started_at > ? OR (started_at = ? AND id > ?)) "
            "ORDER BY started_at, id LIMIT 1",
            (
                run_row["task_id"],
                run_row["started_at"],
                run_row["started_at"],
                run_row["id"],
            ),
        ).fetchone()
        window_end = next_row["started_at"] if next_row else None
        proven = False
        for ev in conn.execute(
            "SELECT ref, created_at FROM evidence "
            "WHERE task_id = ? AND created_at >= ? ORDER BY id",
            (run_row["task_id"], run_row["started_at"]),
        ).fetchall():
            if not (ev["ref"] or "").strip():
                continue
            if window_end is not None and ev["created_at"] >= window_end:
                continue
            proven = True
            break
        if not proven:
            unproven_runs.append(ids.render_id("run", run_row["id"]))
    checks.append(
        Check(
            "success runs without attributable evidence",
            not unproven_runs,
            _bounded_ids(unproven_runs, "run"),
            warn_only=True,
        )
    )

    # 20 (WARN, never fatal). U-H2 (D-v0.2.36): legacy evidence rows whose
    #     ref is blank after normalization (admitted through the pre-U-H2
    #     regex hole). Rows are named by bounded E-XXXX IDs and counts
    #     only, and are never rewritten or deleted — the done gate still
    #     counts them exactly as before.
    blank_ref_rows = [
        ids.render_id("evidence", row["id"])
        for row in conn.execute(
            "SELECT id, ref FROM evidence ORDER BY id"
        ).fetchall()
        if not (row["ref"] or "").strip()
    ]
    checks.append(
        Check(
            "evidence rows with blank refs",
            not blank_ref_rows,
            _bounded_ids(blank_ref_rows, "row"),
            warn_only=True,
        )
    )

    # 21. U-E2 runtime power state: which mode governs this workspace, where
    #     that came from (the missing-file default vs power.json), and what
    #     it degrades. A malformed or unsafe state FAILS here rather than
    #     crashing doctor — reporting the problem is the whole point, since
    #     a malformed state refuses every mode transition until a human
    #     resolves it. Never prints raw JSON, the file's bytes, or a path.
    try:
        state = power.read_state(aos_dir)
    except power.PowerStateError:
        checks.append(
            Check(
                "runtime power state",
                False,
                "malformed or unsafe configuration — run: "
                "python aos.py power status",
            )
        )
    else:
        source = "configured" if state.configured else "default"
        summary = _POWER_SUMMARY[state.mode]
        checks.append(
            Check(
                "runtime power state",
                True,
                f"{state.mode} ({source}; {summary})",
            )
        )

    checks.extend(_memory_claim_checks(conn))
    checks.extend(_memory_graph_checks(conn, aos_dir, aos_root))
    checks.append(_retrieval_benchmark_check())
    checks.extend(_agent_registry_checks(conn))
    checks.extend(_catalog_checks(conn))

    return checks


# ---------------------------------------------------------------------------
# U-A1 governed agent registry integrity (checks 32-34)

def _agent_doctor_label(row) -> str:
    """The identifier doctor echoes for an agent: the name when well-formed
    and not secret-shaped, `agent #id` otherwise."""
    name = row["name"]
    if (
        isinstance(name, str)
        and AGENT_NAME_RE.match(name)
        and not secretscan.scan_secrets(name)
    ):
        return name
    return f"agent #{row['id']}"


def _agent_registry_checks(conn: sqlite3.Connection) -> list[Check]:
    """Three single-purpose checks over the governed agent registry.

    Every diagnostic is a name-or-`agent #id`, a `v<N>`, a verdict from the
    closed vocabulary, or a count. Never a role, mission, document excerpt,
    legacy note, or a hash value.
    """
    from . import passports

    identity_problems: list[str] = []
    history_problems: list[str] = []
    uncovered: list[str] = []

    for row in conn.execute("SELECT * FROM agents ORDER BY id").fetchall():
        label = _agent_doctor_label(row)
        try:
            agent = Agent.from_row(row)
        except (TypeError, KeyError):
            identity_problems.append(f"{label}: unreadable row")
            continue

        # 32. Identity hash.
        state = passports.agent_integrity(agent)
        if state != "ok":
            identity_problems.append(
                f"{label}: "
                + {
                    "malformed": "malformed content hash",
                    "mismatch": "content hash does not match the identity",
                    "unhashable": "identity fields cannot be hashed",
                }[state]
            )

        # 33. Passport history (contiguity, row hashes, document validity and
        #     row↔document consistency, draft shape, pointer resolution) —
        #     the same shared verdicts the no-laundering gate refuses on.
        for problem in passports.history_problems(conn, agent):
            history_problems.append(f"{label}: {problem}")

        # 34 (WARN). Governed coverage: a live identity nothing has declared
        #     for yet. History happening is not an error (D-v0.3.44).
        if (
            agent.lifecycle == "active"
            and agent.current_passport_version is None
        ):
            uncovered.append(label)

    # Orphaned passports cannot exist while the FK stands; this finds the
    # ones that got in if it was ever bypassed.
    for row in conn.execute(
        "SELECT p.id, p.agent_id FROM agent_passports p "
        "LEFT JOIN agents a ON a.id = p.agent_id "
        "WHERE a.id IS NULL ORDER BY p.id"
    ).fetchall():
        history_problems.append(
            f"agent #{row['agent_id']}: passport without an identity row"
        )

    return [
        # 32 (FAIL). Identity hashes verify.
        Check(
            "agent identity hashes verify",
            not identity_problems,
            "; ".join(identity_problems[:UH2_DISPLAY_LIMIT])
            + (
                f" (+{len(identity_problems) - UH2_DISPLAY_LIMIT} more)"
                if len(identity_problems) > UH2_DISPLAY_LIMIT
                else ""
            ),
        ),
        # 33 (FAIL). Passport history intact.
        Check(
            "agent passport history intact",
            not history_problems,
            "; ".join(history_problems[:UH2_DISPLAY_LIMIT])
            + (
                f" (+{len(history_problems) - UH2_DISPLAY_LIMIT} more)"
                if len(history_problems) > UH2_DISPLAY_LIMIT
                else ""
            ),
        ),
        # 34 (WARN, never fatal). Active agents with no published passport —
        #     every migrated legacy agent starts here, honestly.
        Check(
            "active agents without a published passport",
            not uncovered,
            _bounded_ids(uncovered, "agent"),
            warn_only=True,
        ),
    ]



# ---------------------------------------------------------------------------
# U-A2 built-in specialist catalog (checks 35-37)
#
# All three reuse catalog.verify()/catalog.status() — the existing
# read-only verifier and state classification — rather than re-parsing an
# artifact, re-walking the catalog directory, or reading agents/
# agent_passports directly here. Doctor never installs, upgrades, repairs,
# rehashes or mutates the catalog: every check below only reads.

#: catalog.verify()'s problem strings are built from a closed hint
#: vocabulary (catalog._REASON_HINTS) plus a bounded artifact-name or
#: field-path segment — never a document value, a full hash, or arbitrary
#: parsed content. Doctor still never prints that text: it reduces every
#: problem line to the REASON CODE alone, so a malformed catalog cannot
#: smuggle anything but a closed code out through doctor's stdout.
_CATALOG_EXTRA_ARTIFACT_SUFFIX = "not referenced by the catalog manifest"
_CATALOG_INTERNAL_ERROR = "catalog_unavailable"


def _catalog_reason_code(problem: str) -> str:
    from . import catalog

    if problem.endswith(_CATALOG_EXTRA_ARTIFACT_SUFFIX):
        return "extra_artifact"
    for code, hint in catalog._REASON_HINTS.items():
        if problem.endswith(hint):
            return code
    return "other"


def _catalog_verify_check() -> Check:
    """35 (FAIL). The shipped catalog — manifest plus all twelve artifacts —
    verifies as a whole: canonical form, self-digest, structural closure,
    per-document digest/binding/secret-shape, and no unreferenced file.

    `catalog.verify()` never raises by its own contract, but this check
    catches any unexpected exception anyway and reports one bounded FAIL
    rather than crashing doctor.
    """
    from . import catalog

    try:
        problems = catalog.verify()
    except Exception:
        return Check(
            "built-in catalog verified", False, f"1 problem(s): {_CATALOG_INTERNAL_ERROR}"
        )

    if problems:
        codes = sorted({_catalog_reason_code(p) for p in problems})
        return Check(
            "built-in catalog verified",
            False,
            f"{len(problems)} problem(s): " + ", ".join(codes[:UH2_DISPLAY_LIMIT]),
        )

    cat = catalog.catalog()
    passport_count = sum(len(entry.versions) for entry in cat.entries)
    return Check(
        "built-in catalog verified",
        True,
        f"{len(cat.entries)} entry(ies), {passport_count} passport(s)",
    )


def _catalog_identity_check(conn: sqlite3.Connection) -> Check:
    """36 (FAIL). Every catalog-named identity actually installed in this
    ledger is coherent with the shipped catalog: owner/protected/class/
    lifecycle, identity hash, passport-row hashes, issuer, and
    installed-history digests (via `catalog.status()`/`installed_state()`,
    which already covers all of these — no direct SQL here).

    A name collision with a human, imported-human, or legacy identity
    ('blocked') is not a system-owned row at all, so it never fails this
    check; check 37 is where a collision becomes visible.
    """
    from . import catalog

    try:
        rows = catalog.status(conn)
    except Exception:
        return Check(
            "installed catalog identities verified",
            False,
            f"1 problem(s): {_CATALOG_INTERNAL_ERROR}",
        )

    bad = [row for row in rows if row["state"] in ("diverged", "tampered")]
    if bad:
        shown = [f"{row['agent']} ({row['state']})" for row in bad[:UH2_DISPLAY_LIMIT]]
        extra = len(bad) - UH2_DISPLAY_LIMIT
        detail = f"{len(bad)} problem(s): " + ", ".join(shown)
        if extra > 0:
            detail += f" (+{extra} more)"
        return Check("installed catalog identities verified", False, detail)

    installed = sum(1 for row in rows if row["state"] in ("installed", "upgradable"))
    return Check("installed catalog identities verified", True, f"{installed} installed")


def _catalog_availability_check(conn: sqlite3.Connection) -> Check:
    """37 (WARN, never fatal). An actionable catalog-install condition: an
    upgradable entry, or a name collision with a human, imported-human, or
    legacy identity. Never fires merely because the catalog was never
    installed — an honest workspace that has never run
    `agent catalog install` stays silent and healthy.
    """
    from . import catalog

    try:
        rows = catalog.status(conn)
    except Exception:
        return Check(
            "catalog entries available to install",
            False,
            f"1 problem(s): {_CATALOG_INTERNAL_ERROR}",
            warn_only=True,
        )

    actionable = [row for row in rows if row["state"] in ("upgradable", "blocked")]
    if not actionable:
        return Check(
            "catalog entries available to install",
            True,
            "no actionable catalog upgrades or collisions",
            warn_only=True,
        )

    shown = [f"{row['agent']} ({row['state']})" for row in actionable[:UH2_DISPLAY_LIMIT]]
    extra = len(actionable) - UH2_DISPLAY_LIMIT
    detail = f"{len(actionable)} actionable: " + ", ".join(shown)
    if extra > 0:
        detail += f" (+{extra} more)"
    return Check("catalog entries available to install", False, detail, warn_only=True)


def _catalog_checks(conn: sqlite3.Connection) -> list[Check]:
    """The three U-A2 built-in-catalog lines (checks 35-37)."""
    return [
        _catalog_verify_check(),
        _catalog_identity_check(conn),
        _catalog_availability_check(conn),
    ]


def _retrieval_benchmark_check() -> Check:
    """31. U-M5's one line: the retrieval benchmark registry is intact
    (M5.14).

    ONE check, and it does not run a benchmark. Doctor is a health check, not
    a CI job; a doctor that evaluated nineteen cases on every invocation would
    be a doctor people stop running.

    Unlike U-X1, U-M5 ships no `verify-registry` command — so without this
    line a drifted projection would be invisible outside the test suite, which
    is exactly the justification for spending a check on it.

    The PASSING detail is a function of the EMBEDDED definitions alone, and
    deliberately so: doctor's stdout is an entrypoint-parity surface (a script
    and aos.pyz must print the same bytes), and aos.pyz legitimately has no
    retrieval_benchmarks/ directory to compare against (D-v0.3.2/D-v0.3.61).
    A detail that said "compared 3 artifacts" in a checkout and "nothing to
    compare" in the archive would make one true sentence out of two different
    doctors. The embedded definitions ARE canonical in both, so the line
    reports what is true in both and stays silent about the rest.

    Where a source checkout EXISTS the projection is still compared, and drift
    still FAILS — that comparison just cannot be what the healthy line says.

    Names files, counts and conditions. Never a fixture body, a query or a
    synthetic value.
    """
    from . import retrieval

    problems = retrieval.verify_embedded()
    source = retrieval.source_benchmarks_dir()
    if source is not None:
        problems += retrieval.verify_source_benchmarks(source)
    if problems:
        return Check(
            "retrieval benchmark registry verified",
            False,
            _bounded_problems(problems)
            + " — regenerate: python3 tools/gen_retrieval_benchmarks.py",
        )
    return Check(
        "retrieval benchmark registry verified",
        True,
        f"{len(retrieval.benchmark_names())} benchmark(s), "
        f"{sum(len(d['cases']) for d in retrieval.registry().values())} case(s)",
    )


# ---------------------------------------------------------------------------
# U-M2 memory claim integrity (checks 22-25; contract M2.10)

def _memory_claim_checks(conn: sqlite3.Connection) -> list[Check]:
    """Four single-purpose checks over the v2 memory claims.

    Every diagnostic below is an M-XXXX / E-XXXX id, a status name from the
    closed vocabulary, or a count. Never a key, value, source, evidence ref
    or a hash — a check that leaks the row it is complaining about would be
    a worse problem than the row.
    """
    now = utils.utc_now_iso()
    claim_problems: list[str] = []
    pinned_ineligible: list[str] = []
    expired_not_retired: list[str] = []

    for row in conn.execute("SELECT * FROM memory ORDER BY id").fetchall():
        hid = ids.render_id("memory", row["id"])
        problems: list[str] = []
        if row["status"] not in MEMORY_STATUSES:
            # The status VALUE is not echoed: it is stored data, and stored
            # data is exactly what must not reach a diagnostic line.
            problems.append("unknown status")
        if row["pinned"] not in (0, 1):
            problems.append("pinned is not 0 or 1")

        try:
            item = MemoryItem.from_row(row)
        except (TypeError, KeyError):
            claim_problems.append(f"{hid}: unreadable row")
            continue

        state = ops.claim_integrity(conn, item)
        if state != "ok":
            problems.append(
                {
                    "malformed": "malformed content hash",
                    "mismatch": "content hash does not match the claim",
                    "unhashable": "claim fields cannot be hashed",
                }[state]
            )

        expired = row["valid_until"] is not None and not (
            row["valid_until"] > now
        )
        if row["status"] == MEMORY_STATUS_RETIRED:
            # Retired must be JUSTIFIED: something must have retired it.
            if row["superseded_by"] is None and not expired:
                problems.append("retired but neither superseded nor expired")
        elif row["superseded_by"] is not None:
            # Supersession retires transactionally (M2.7), so no honest path
            # leaves a superseded claim non-retired.
            problems.append("superseded but not retired")

        if row["superseded_by"] is not None and row["superseded_by"] == row["id"]:
            problems.append("superseded by itself")

        if problems:
            claim_problems.append(f"{hid}: " + ", ".join(problems))

        if row["pinned"] and not ops.claim_is_eligible(item, now):
            pinned_ineligible.append(hid)
        if expired and row["status"] != MEMORY_STATUS_RETIRED:
            expired_not_retired.append(hid)

    link_problems: list[str] = []
    for row in conn.execute(
        "SELECT me.memory_id, me.evidence_id, m.id AS m_ref, e.id AS e_ref "
        "FROM memory_evidence me "
        "LEFT JOIN memory m ON m.id = me.memory_id "
        "LEFT JOIN evidence e ON e.id = me.evidence_id "
        "ORDER BY me.memory_id, me.evidence_id"
    ).fetchall():
        hid = ids.render_id("memory", row["memory_id"])
        ehid = ids.render_id("evidence", row["evidence_id"])
        if row["m_ref"] is None:
            link_problems.append(f"{hid} → missing memory claim")
        if row["e_ref"] is None:
            link_problems.append(f"{hid} → missing evidence {ehid}")
    # Duplicate links are impossible while the composite primary key stands;
    # this finds the ones that got in if it was ever bypassed.
    for row in conn.execute(
        "SELECT memory_id, evidence_id, COUNT(*) AS n FROM memory_evidence "
        "GROUP BY memory_id, evidence_id HAVING n > 1 "
        "ORDER BY memory_id, evidence_id"
    ).fetchall():
        link_problems.append(
            f"{ids.render_id('memory', row['memory_id'])} → "
            f"{ids.render_id('evidence', row['evidence_id'])} × {row['n']}"
        )

    return [
        # 22. Claim shape and integrity.
        Check(
            "memory claims are well-formed",
            not claim_problems,
            "; ".join(claim_problems[:UH2_DISPLAY_LIMIT])
            + (
                f" (+{len(claim_problems) - UH2_DISPLAY_LIMIT} more)"
                if len(claim_problems) > UH2_DISPLAY_LIMIT
                else ""
            ),
        ),
        # 23. Evidence links resolve and are unique.
        Check(
            "memory evidence links resolve",
            not link_problems,
            "; ".join(link_problems[:UH2_DISPLAY_LIMIT])
            + (
                f" (+{len(link_problems) - UH2_DISPLAY_LIMIT} more)"
                if len(link_problems) > UH2_DISPLAY_LIMIT
                else ""
            ),
        ),
        # 24 (WARN). Pinned but ineligible: honestly reachable (pin, then
        #     retire; pin, then the expiry passes) and harmless — but the
        #     human who pinned it deserves to hear that it is not retrieved.
        Check(
            "pinned claims eligible for retrieval",
            not pinned_ineligible,
            _bounded_ids(pinned_ineligible, "claim"),
            warn_only=True,
        ),
        # 25 (WARN). Past valid_until but not retired. Expiry is TEMPORAL —
        #     a claim crosses its own valid_until with no write at all, and
        #     `--valid-until` accepts a past date. So this is a fact worth
        #     surfacing, never a failure: a check that turns red because a
        #     day passed is a broken check (M2.7).
        Check(
            "non-retired claims past their valid_until",
            not expired_not_retired,
            _bounded_ids(expired_not_retired, "claim"),
            warn_only=True,
        ),
    ]


# ---------------------------------------------------------------------------
# U-M3 memory graph integrity (checks 26-30; contract M3.14)


def _bounded_problems(problems: list[str]) -> str:
    """The shared detail renderer for the graph checks: at most
    UH2_DISPLAY_LIMIT findings, then a count. Output derived from ledger rows
    stays bounded, however damaged the ledger is."""
    if not problems:
        return ""
    extra = len(problems) - UH2_DISPLAY_LIMIT
    return "; ".join(problems[:UH2_DISPLAY_LIMIT]) + (
        f" (+{extra} more)" if extra > 0 else ""
    )


def _rank_or_none(level) -> int | None:
    """The sensitivity ladder position, or None for a value that is not on it.

    Never raises and never echoes the value: an unknown sensitivity is a
    finding for check 26 to report by ID, not an exception that takes doctor
    down with it.
    """
    if not isinstance(level, str):
        return None
    try:
        return models.sensitivity_rank(level)
    except AosError:
        return None


def _sensitivity_check(conn: sqlite3.Connection) -> Check:
    """26. Every claim's and source's sensitivity is on the closed ladder.

    Reachable only by editing the file — the CHECK constraints refuse the rest
    — which is exactly why it is worth checking. A row whose sensitivity is
    unreadable is a row whose exclusion from packs cannot be reasoned about.
    """
    problems: list[str] = []
    for table, entity in (("memory", "memory"), ("memory_sources", "memory_source")):
        for row in conn.execute(
            f"SELECT id, sensitivity FROM {table} ORDER BY id"
        ).fetchall():
            if _rank_or_none(row["sensitivity"]) is None:
                # The VALUE is not echoed: it is stored data, and stored data
                # is exactly what must not reach a diagnostic line.
                problems.append(
                    f"{ids.render_id(entity, row['id'])}: unknown sensitivity"
                )
    return Check(
        "memory sensitivity values are known",
        not problems,
        _bounded_problems(problems),
    )


def _source_checks(conn: sqlite3.Connection) -> Check:
    """27. Sources are well-formed: shape, targets, window, hash."""
    problems: list[str] = []
    for row in conn.execute("SELECT * FROM memory_sources ORDER BY id").fetchall():
        hid = ids.render_id("memory_source", row["id"])
        found: list[str] = []
        try:
            item = models.MemorySource.from_row(row)
        except (TypeError, KeyError):
            problems.append(f"{hid}: unreadable row")
            continue

        if item.source_kind not in models.MEMORY_SOURCE_KINDS:
            found.append("unknown source kind")
        elif item.source_kind == models.MEMORY_SOURCE_KIND_EVIDENCE:
            if item.evidence_id is None or item.locator is not None:
                found.append("evidence source with a locator or no evidence id")
        elif item.evidence_id is not None or item.locator is None:
            found.append("non-evidence source with an evidence id or no locator")

        if item.evidence_id is not None and conn.execute(
            "SELECT 1 FROM evidence WHERE id = ?", (item.evidence_id,)
        ).fetchone() is None:
            # The evidence ID is named; the evidence row is never read.
            found.append(
                f"missing evidence {ids.render_id('evidence', item.evidence_id)}"
            )
        if item.project_id is not None and conn.execute(
            "SELECT 1 FROM projects WHERE id = ?", (item.project_id,)
        ).fetchone() is None:
            found.append("missing project")

        if (
            isinstance(item.valid_from, str)
            and isinstance(item.valid_until, str)
            and item.valid_from > item.valid_until
        ):
            found.append("validity window is inverted")

        state = ops.source_integrity(item)
        if state != "ok":
            found.append(_INTEGRITY_PROBLEM[state])

        if found:
            problems.append(f"{hid}: " + ", ".join(found))
    return Check(
        "memory sources are well-formed", not problems, _bounded_problems(problems)
    )


def _source_link_checks(conn: sqlite3.Connection) -> Check:
    """28. Source links resolve, are unique, and respect project/sensitivity.

    The compatibility rules are re-checked here rather than trusted: they are
    enforced in `ops` before every write, so a violation found now means a
    writer bypassed `ops` — which is the whole reason to look.
    """
    problems: list[str] = []
    for row in conn.execute(
        "SELECT l.*, m.project_id AS m_project, m.sensitivity AS m_sensitivity, "
        "m.id AS m_ref, s.project_id AS s_project, "
        "s.sensitivity AS s_sensitivity, s.id AS s_ref "
        "FROM memory_source_links l "
        "LEFT JOIN memory m ON m.id = l.memory_id "
        "LEFT JOIN memory_sources s ON s.id = l.source_id "
        "ORDER BY l.id"
    ).fetchall():
        hid = ids.render_id("memory_source_link", row["id"])
        found: list[str] = []
        if row["m_ref"] is None:
            found.append(
                f"missing claim {ids.render_id('memory', row['memory_id'])}"
            )
        if row["s_ref"] is None:
            found.append(
                f"missing source {ids.render_id('memory_source', row['source_id'])}"
            )
        if row["relation"] not in models.MEMORY_SOURCE_RELATIONS:
            found.append("unknown relation")

        if row["m_ref"] is not None and row["s_ref"] is not None:
            if (
                row["s_project"] is not None
                and row["s_project"] != row["m_project"]
            ):
                found.append("project source linked outside its project")
            source_rank = _rank_or_none(row["s_sensitivity"])
            claim_rank = _rank_or_none(row["m_sensitivity"])
            if (
                source_rank is not None
                and claim_rank is not None
                and source_rank > claim_rank
            ):
                found.append("source is more sensitive than its claim")

        try:
            link = models.MemorySourceLink.from_row(
                {k: row[k] for k in (
                    "id", "memory_id", "source_id", "relation", "created_at",
                    "content_sha256",
                )}
            )
        except (TypeError, KeyError):
            found.append("unreadable row")
        else:
            state = ops.source_link_integrity(link)
            if state != "ok":
                found.append(_INTEGRITY_PROBLEM[state])

        if found:
            problems.append(f"{hid}: " + ", ".join(found))

    # Duplicates are impossible while the UNIQUE constraint stands; this finds
    # the ones that got in if it was ever bypassed.
    for row in conn.execute(
        "SELECT memory_id, source_id, relation, COUNT(*) AS n "
        "FROM memory_source_links GROUP BY memory_id, source_id, relation "
        "HAVING n > 1 ORDER BY memory_id, source_id, relation"
    ).fetchall():
        problems.append(
            f"{ids.render_id('memory', row['memory_id'])} → "
            f"{ids.render_id('memory_source', row['source_id'])} × {row['n']}"
        )
    return Check(
        "memory source links resolve", not problems, _bounded_problems(problems)
    )


def _edge_checks(conn: sqlite3.Connection) -> Check:
    """29. Edges are well-formed: endpoints, relation, canonical form, window,
    project scope, hash."""
    problems: list[str] = []
    for row in conn.execute(
        "SELECT e.*, f.id AS from_ref, f.project_id AS from_project, "
        "t.id AS to_ref, t.project_id AS to_project FROM memory_edges e "
        "LEFT JOIN memory f ON f.id = e.from_memory_id "
        "LEFT JOIN memory t ON t.id = e.to_memory_id ORDER BY e.id"
    ).fetchall():
        hid = ids.render_id("memory_edge", row["id"])
        found: list[str] = []
        try:
            edge = models.MemoryEdge.from_row(
                {k: row[k] for k in (
                    "id", "from_memory_id", "to_memory_id", "relation",
                    "valid_from", "valid_until", "created_at", "content_sha256",
                )}
            )
        except (TypeError, KeyError):
            problems.append(f"{hid}: unreadable row")
            continue

        if row["from_ref"] is None:
            found.append(
                f"missing claim {ids.render_id('memory', edge.from_memory_id)}"
            )
        if row["to_ref"] is None:
            found.append(
                f"missing claim {ids.render_id('memory', edge.to_memory_id)}"
            )
        if edge.from_memory_id == edge.to_memory_id:
            found.append("self-edge")
        if edge.relation not in models.MEMORY_EDGE_RELATIONS:
            found.append("unknown relation")
        elif (
            edge.relation in models.MEMORY_EDGE_SYMMETRIC
            and isinstance(edge.from_memory_id, int)
            and isinstance(edge.to_memory_id, int)
            and edge.from_memory_id > edge.to_memory_id
        ):
            # A symmetric edge stored the wrong way round is not cosmetic: the
            # UNIQUE constraint no longer collides with its mirror image, so
            # the same fact can be stored twice (D-v0.3.36).
            found.append("symmetric edge is not canonically ordered")
        if (
            row["from_project"] is not None
            and row["to_project"] is not None
            and row["from_project"] != row["to_project"]
        ):
            found.append("edge crosses projects")
        if (
            isinstance(edge.valid_from, str)
            and isinstance(edge.valid_until, str)
            and edge.valid_from > edge.valid_until
        ):
            found.append("validity window is inverted")

        state = ops.edge_integrity(edge)
        if state != "ok":
            found.append(_INTEGRITY_PROBLEM[state])

        if found:
            problems.append(f"{hid}: " + ", ".join(found))

    for row in conn.execute(
        "SELECT from_memory_id, to_memory_id, relation, COUNT(*) AS n "
        "FROM memory_edges GROUP BY from_memory_id, to_memory_id, relation "
        "HAVING n > 1 ORDER BY from_memory_id, to_memory_id, relation"
    ).fetchall():
        problems.append(
            f"{ids.render_id('memory', row['from_memory_id'])} → "
            f"{ids.render_id('memory', row['to_memory_id'])} × {row['n']}"
        )
    return Check(
        "memory edges are well-formed", not problems, _bounded_problems(problems)
    )


def _restricted_context_check(
    conn: sqlite3.Connection, aos_dir: Path, aos_root: Path
) -> Check:
    """30 (WARN). Restricted claim text sitting in a generated context surface.

    WARN, never FAIL (D-v0.3.46): a pack built BEFORE a claim was classified
    restricted legitimately contains it. The operator did nothing wrong and no
    invariant was violated at the time — but it is a real leak on disk they
    should know about, and `pack build` / `sync` regenerate it away. A check
    that turns red because history happened is a broken check.

    The claim's key is READ (it is in the same database) and never PRINTED:
    the finding is the claim id and the file's name, never the text that
    matched or the line it sat on.
    """
    restricted = [
        (row["id"], row["key"])
        for row in conn.execute(
            "SELECT id, key FROM memory WHERE sensitivity = ? ORDER BY id",
            (MEMORY_SENSITIVITY_RESTRICTED,),
        ).fetchall()
        if isinstance(row["key"], str) and row["key"].strip()
    ]
    if not restricted:
        return Check("restricted claims absent from generated context", True, "")

    findings: list[str] = []
    surfaces = list((aos_dir / "packs").glob("*.md")) + list(
        (aos_root / "Memory").glob("*.md")
    )
    for path in sorted(surfaces):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue  # unreadable file is check 2's problem, not this one's
        for memory_id, key in restricted:
            if key in text:
                findings.append(
                    f"{ids.render_id('memory', memory_id)} in {path.name}"
                )
    return Check(
        "restricted claims absent from generated context",
        not findings,
        _bounded_problems(findings),
        warn_only=True,
    )


#: How an integrity verdict reads in a diagnostic. Reason codes, never values.
_INTEGRITY_PROBLEM = {
    "malformed": "malformed content hash",
    "mismatch": "content hash does not match the record",
    "unhashable": "record fields cannot be hashed",
}


def _memory_graph_checks(
    conn: sqlite3.Connection, aos_dir: Path, aos_root: Path
) -> list[Check]:
    """The five U-M3 lines (checks 26-30).

    Every diagnostic below is an M-/MS-/ML-/ME-/E-XXXX id, a reason code from
    a fixed set, a generated file's name, or a count. Never a claim key or
    value, a source locator or provenance, an evidence ref, a full hash, or an
    arbitrary SQLite value — a check that leaked the row it is complaining
    about would be a worse problem than the row.
    """
    return [
        _sensitivity_check(conn),
        _source_checks(conn),
        _source_link_checks(conn),
        _edge_checks(conn),
        _restricted_context_check(conn, aos_dir, aos_root),
    ]
