"""Health checks. Exit 0 when everything passes; exit 1 with the list of
failed checks otherwise (wiring in cli.py).

Night-1 checks: DB exists · required folders exist · Obsidian Home.md
exists · every done task has evidence unless an override event exists ·
generated wikilinks point to existing generated notes · nothing outside
AOS/ was generated by sync.

Weekend hardening adds: schema_version supported · task statuses inside the
vocabulary · handoffs reference existing tasks · task-linked decisions
reference existing tasks · memory supersede pointers resolve · packs
reference existing tasks and their files exist on disk.
"""

from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from . import db, ids, obsidian, utils
from .models import TASK_STATUSES

_WIKILINK = re.compile(r"\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]")

_NOTE_PATTERNS = {
    "Tasks": re.compile(r"^T-[0-9]{4,}$"),
    "Runs": re.compile(r"^R-[0-9]{4,}$"),
    "Decisions": re.compile(r"^D-[0-9]{4,}$"),
    "Evidence": re.compile(r"^E-[0-9]{4,}$"),
    "Handoffs": re.compile(r"^H-[0-9]{4,}$"),
    "Memory": re.compile(r"^M-[0-9]{4,}$"),
    "Projects": re.compile(r"^[a-z0-9][a-z0-9._-]*$", re.ASCII),
    "Reviews": re.compile(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}$"),
}


@dataclass
class Check:
    name: str
    ok: bool
    detail: str = ""


def _is_hidden(path: Path, base: Path) -> bool:
    """True when any component below `base` starts with '.' (e.g. the
    .obsidian folder Obsidian creates at the vault root)."""
    return any(
        part.startswith(".") for part in path.relative_to(base).parts
    )


def run_checks(conn: sqlite3.Connection, aos_dir: Path) -> list[Check]:
    checks: list[Check] = []
    aos_root = obsidian.vault_aos_dir(aos_dir)

    # 1. DB exists.
    db_path = aos_dir / utils.DB_FILENAME
    checks.append(Check("database exists", db_path.is_file(), str(db_path)))

    # 2. Required folders exist.
    required = [aos_dir / name for name in obsidian.WORKSPACE_DIRS]
    required.append(aos_root)
    required += [aos_root / name for name in obsidian.ENTITY_DIRS]
    missing = [str(p) for p in required if not p.is_dir()]
    checks.append(
        Check(
            "required folders exist",
            not missing,
            "; ".join(f"missing {m}" for m in missing),
        )
    )

    # 3. Obsidian Home.md exists.
    home = aos_root / "Home.md"
    checks.append(Check("Home.md exists", home.is_file(), str(home)))

    # 4. Every done task has evidence unless an override event exists.
    offenders = []
    for row in conn.execute(
        "SELECT t.id FROM tasks t WHERE t.status = 'done' "
        "AND NOT EXISTS (SELECT 1 FROM evidence e WHERE e.task_id = t.id) "
        "AND NOT EXISTS (SELECT 1 FROM events ev WHERE ev.entity = 'task' "
        "AND ev.entity_id = t.id AND ev.action = 'done_override') "
        "ORDER BY t.id"
    ).fetchall():
        offenders.append(ids.render_id("task", row["id"]))
    checks.append(
        Check(
            "done tasks have evidence (or a logged override)",
            not offenders,
            "no evidence and no override event: " + ", ".join(offenders)
            if offenders
            else "",
        )
    )

    # 5. Generated wikilinks resolve to existing generated notes.
    broken = []
    if aos_root.is_dir():
        stems = {
            path.stem
            for path in aos_root.rglob("*.md")
            if not _is_hidden(path, aos_root)
        }
        for path in sorted(aos_root.rglob("*.md")):
            if _is_hidden(path, aos_root):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                broken.append(
                    f"{path.relative_to(aos_root).as_posix()}: not valid UTF-8"
                )
                continue
            for match in _WIKILINK.finditer(text):
                target = match.group(1).strip()
                if target not in stems:
                    broken.append(
                        f"{path.relative_to(aos_root).as_posix()} → [[{target}]]"
                    )
    checks.append(
        Check(
            "wikilinks resolve to generated notes",
            not broken,
            "; ".join(broken[:10]),
        )
    )

    # 6. Nothing outside AOS/ was generated by sync, and everything inside
    #    AOS/ is a recognized generated note. (Hidden entries such as
    #    Obsidian's own .obsidian/ folder are the user's, not sync's.)
    strays = []
    vault = aos_dir / obsidian.VAULT_DIRNAME
    if vault.is_dir():
        for path in sorted(vault.rglob("*")):
            if not path.is_file() or _is_hidden(path, vault):
                continue
            if aos_root not in path.parents:
                strays.append(path.relative_to(vault).as_posix())
                continue
            rel = path.relative_to(aos_root)
            if rel.as_posix() in ("Home.md", "CONVENTIONS.md"):
                continue
            pattern = (
                _NOTE_PATTERNS.get(rel.parts[0]) if len(rel.parts) == 2 else None
            )
            if (
                pattern is None
                or path.suffix != ".md"
                or not pattern.match(path.stem)
            ):
                strays.append(rel.as_posix())
    checks.append(
        Check(
            "mirror contains only generated AOS/ notes",
            not strays,
            "; ".join(strays[:10]),
        )
    )

    # 7. schema_version supported by this build.
    version = db.get_meta(conn, "schema_version")
    checks.append(
        Check(
            "schema_version supported",
            version == db.SCHEMA_VERSION,
            ""
            if version == db.SCHEMA_VERSION
            else f"found {version!r}, this build supports {db.SCHEMA_VERSION!r}",
        )
    )

    # 8. No task carries a status outside the vocabulary.
    marks = ",".join("?" * len(TASK_STATUSES))
    bad_status = conn.execute(
        f"SELECT id, status FROM tasks WHERE status NOT IN ({marks}) "
        "ORDER BY id",
        TASK_STATUSES,
    ).fetchall()
    checks.append(
        Check(
            "task statuses inside the vocabulary",
            not bad_status,
            "; ".join(
                f"{ids.render_id('task', row['id'])}: {row['status']!r}"
                for row in bad_status[:10]
            ),
        )
    )

    # 9. Handoffs point to existing tasks.
    orphan_handoffs = conn.execute(
        "SELECT h.id FROM handoffs h LEFT JOIN tasks t ON t.id = h.task_id "
        "WHERE t.id IS NULL ORDER BY h.id"
    ).fetchall()
    checks.append(
        Check(
            "handoffs reference existing tasks",
            not orphan_handoffs,
            "; ".join(
                ids.render_id("handoff", row["id"])
                for row in orphan_handoffs[:10]
            ),
        )
    )

    # 10. Task-linked decisions point to existing tasks.
    orphan_decisions = conn.execute(
        "SELECT d.id FROM decisions d LEFT JOIN tasks t ON t.id = d.task_id "
        "WHERE d.task_id IS NOT NULL AND t.id IS NULL ORDER BY d.id"
    ).fetchall()
    checks.append(
        Check(
            "task-linked decisions reference existing tasks",
            not orphan_decisions,
            "; ".join(
                ids.render_id("decision", row["id"])
                for row in orphan_decisions[:10]
            ),
        )
    )

    # 11. Memory supersede pointers resolve to existing memory rows.
    dangling_memory = conn.execute(
        "SELECT m.id, m.superseded_by FROM memory m "
        "LEFT JOIN memory s ON s.id = m.superseded_by "
        "WHERE m.superseded_by IS NOT NULL AND s.id IS NULL ORDER BY m.id"
    ).fetchall()
    checks.append(
        Check(
            "memory supersede pointers resolve",
            not dangling_memory,
            "; ".join(
                f"{ids.render_id('memory', row['id'])} → missing "
                f"{ids.render_id('memory', row['superseded_by'])}"
                for row in dangling_memory[:10]
            ),
        )
    )

    # 12. Packs reference existing tasks and their files exist on disk.
    pack_problems = []
    for row in conn.execute(
        "SELECT p.id, p.path, t.id AS task_ref FROM packs p "
        "LEFT JOIN tasks t ON t.id = p.task_id ORDER BY p.id"
    ).fetchall():
        pack_hid = ids.render_id("pack", row["id"])
        if row["task_ref"] is None:
            pack_problems.append(f"{pack_hid} → missing task")
        elif not (aos_dir / row["path"]).is_file():
            pack_problems.append(f"{pack_hid} → missing file {row['path']}")
    checks.append(
        Check(
            "packs reference existing tasks and files",
            not pack_problems,
            "; ".join(pack_problems[:10]),
        )
    )

    return checks
