#!/usr/bin/env python3
"""Fail-closed canonical byte-grammar verifier for .github/workflows/ci.yml.

Contract: agentic-os-v0.4-u-p2-delivery-gate-contract.md §12 (D-v0.4.41).

This is deliberately NOT a general YAML parser or an Actions linter, and it does
NOT scan for forbidden substrings. It affirmatively recognizes the ONE frozen
canonical workflow: the security decision is exact equality against an embedded
canonical byte representation (`CANONICAL_TEXT`), so the file is accepted only
when every byte and construct belongs to the single frozen grammar, and any
deviation — an anchor, alias, custom tag, duplicate key, document marker,
multi-document stream, flow-style collection, quoted/escaped key, alternate
boolean spelling, job-level `permissions:` block, local action, reusable
workflow, multiline/folded `uses:`, unexpected block scalar, unknown
job/step/key/ordering, or shell indirection replacing a frozen command — fails
closed. Because the canonical text is clean, the classification checks layered
on top can never cause a false accept: they only *refine* a rejection into the
most specific reason code, defaulting to `unexpected_workflow_shape`. Even if a
classification check had a gap, the equality backstop still rejects.

Standard library only. Opens no socket, spawns no subprocess, mutates nothing,
and stays total: a hostile or corrupt file yields findings, never a traceback.

Interface:

    python3 tools/verify_ci_workflow.py
    python3 tools/verify_ci_workflow.py --workflow .github/workflows/ci.yml

Exit 0 only with zero findings; 1 with findings (one reason code per line on
stdout, deterministically ordered by (reason, locus)); 2 on a usage error.
Diagnostics are value-free and bounded: a reason code from the closed 20-code
vocabulary, optionally followed by a closed-set locus (a frozen job id, a frozen
trigger name, or `line:<n>`). Arbitrary workflow content is never echoed, so a
hostile workflow cannot use the verifier as an output channel.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Frozen canonical workflow — the embedded authority (contract §6, §10). This
# tuple is generated byte-for-byte from the frozen .github/workflows/ci.yml;
# tests/test_v04_delivery_gate.py::test_canonical_workflow_passes proves it has
# not drifted from the real file.

_CANONICAL_LINES = (
    'name: ci',
    '',
    'on:',
    '  pull_request:',
    '    branches: [main]',
    '  push:',
    '    branches: [main]',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'env:',
    '  PYTHONDONTWRITEBYTECODE: "1"',
    '',
    'defaults:',
    '  run:',
    '    shell: bash',
    '',
    'concurrency:',
    '  group: ci-${{ github.ref }}',
    "  cancel-in-progress: ${{ github.event_name == 'pull_request' }}",
    '',
    'jobs:',
    '  workflow-integrity:',
    '    name: workflow-integrity',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 10',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.12"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Verify workflow integrity',
    '        run: python3 tools/verify_ci_workflow.py',
    '',
    '  tests-python-3-12:',
    '    name: tests-python-3.12',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.12"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Compile all sources',
    '        run: python3 -m compileall -q agentic_os tests tools aos.py aos_hooks.py',
    '      - name: Run the full test suite',
    '        run: python3 -m unittest discover -s tests',
    '      - name: Verify protocol projection',
    '        run: python3 tools/gen_protocols.py',
    '      - name: Assert a clean working tree',
    '        run: |',
    '          set -euo pipefail',
    '          git diff --exit-code',
    '          test -z "$(git status --porcelain)"',
    '',
    '  tests-python-3-14:',
    '    name: tests-python-3.14',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.14"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Compile all sources',
    '        run: python3 -m compileall -q agentic_os tests tools aos.py aos_hooks.py',
    '      - name: Run the full test suite',
    '        run: python3 -m unittest discover -s tests',
    '      - name: Verify protocol projection',
    '        run: python3 tools/gen_protocols.py',
    '      - name: Assert a clean working tree',
    '        run: |',
    '          set -euo pipefail',
    '          git diff --exit-code',
    '          test -z "$(git status --porcelain)"',
    '',
    '  distribution-smoke-python-3-12:',
    '    name: distribution-smoke-python-3.12',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.12"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Install pinned build tools',
    '        run: |',
    '          set -euo pipefail',
    '          python3 -m pip install pip==26.1.2',
    '          python3 -m pip install build==1.5.0 setuptools==83.0.0 packaging==26.2 pyproject_hooks==1.2.0',
    '          python3 -m pip freeze',
    '      - name: Build the wheel',
    '        run: python3 -m build --wheel --no-isolation --outdir "$RUNNER_TEMP/dist"',
    '      - name: Assert wheel membership',
    '        run: |',
    '          set -euo pipefail',
    "          python3 - <<'PY'",
    '          import glob, os, re, sys, zipfile',
    '          runner_temp = os.environ["RUNNER_TEMP"]',
    '          wheels = sorted(glob.glob(os.path.join(runner_temp, "dist", "agentic_os-*.whl")))',
    '          if len(wheels) != 1:',
    '              print("wheel: expected exactly one wheel, found", len(wheels))',
    '              sys.exit(1)',
    '          passport = re.compile(r"^agentic_os/catalog/[a-z][a-z0-9._-]*\\.v[1-9][0-9]*\\.passport\\.json$")',
    '          dist_info = re.compile(r"^agentic_os-[^/]+\\.dist-info/.+$")',
    '          def allowed(name):',
    '              if name.startswith("agentic_os/") and name.endswith(".py"):',
    '                  return True',
    '              if name == "agentic_os/catalog/manifest.json":',
    '                  return True',
    '              return passport.match(name) is not None or dist_info.match(name) is not None',
    '          with zipfile.ZipFile(wheels[0]) as archive:',
    '              members = [n for n in archive.namelist() if not n.endswith("/")]',
    '              wheel_catalog = {}',
    '              for name in members:',
    '                  if not allowed(name):',
    '                      print("wheel: unexpected member", name)',
    '                      sys.exit(1)',
    '                  if name.startswith("agentic_os/catalog/") and name.endswith(".json"):',
    '                      wheel_catalog[os.path.basename(name)] = archive.read(name)',
    '          source_catalog = {}',
    '          for path in sorted(glob.glob("agentic_os/catalog/*.json")):',
    '              with open(path, "rb") as handle:',
    '                  source_catalog[os.path.basename(path)] = handle.read()',
    '          if len(source_catalog) != 13:',
    '              print("wheel: expected 13 source catalog json files, found", len(source_catalog))',
    '              sys.exit(1)',
    '          if wheel_catalog != source_catalog:',
    '              print("wheel: catalog json does not byte-match the source tree")',
    '              sys.exit(1)',
    '          print("wheel membership OK:", len(members), "members")',
    '          PY',
    '      - name: Install the wheel and smoke the console script',
    '        run: |',
    '          set -euo pipefail',
    '          python3 -m venv "$RUNNER_TEMP/venv"',
    '          "$RUNNER_TEMP/venv/bin/python" -m pip install --no-deps "$RUNNER_TEMP"/dist/agentic_os-*.whl',
    '          cd "$RUNNER_TEMP"',
    '          "$RUNNER_TEMP/venv/bin/aos" --help',
    '          mkdir -p "$RUNNER_TEMP/ws-wheel"',
    '          "$RUNNER_TEMP/venv/bin/aos" --root "$RUNNER_TEMP/ws-wheel" init',
    '          "$RUNNER_TEMP/venv/bin/aos" --root "$RUNNER_TEMP/ws-wheel" status',
    '          "$RUNNER_TEMP/venv/bin/aos" --root "$RUNNER_TEMP/ws-wheel" doctor',
    '          "$RUNNER_TEMP/venv/bin/aos" protocol verify-registry',
    '      - name: Build the zipapp',
    '        run: python3 tools/build_zipapp.py --output "$RUNNER_TEMP/aos.pyz"',
    '      - name: Assert zipapp membership',
    '        run: |',
    '          set -euo pipefail',
    "          python3 - <<'PY'",
    '          import os, re, sys, zipfile',
    '          runner_temp = os.environ["RUNNER_TEMP"]',
    '          passport = re.compile(r"^agentic_os/catalog/[a-z][a-z0-9._-]*\\.v[1-9][0-9]*\\.passport\\.json$")',
    '          def allowed(name):',
    '              if name == "__main__.py":',
    '                  return True',
    '              if name.startswith("agentic_os/") and name.endswith(".py"):',
    '                  return True',
    '              if name == "agentic_os/catalog/manifest.json":',
    '                  return True',
    '              return passport.match(name) is not None',
    '          with zipfile.ZipFile(os.path.join(runner_temp, "aos.pyz")) as archive:',
    '              members = [n for n in archive.namelist() if not n.endswith("/")]',
    '              for name in members:',
    '                  if not allowed(name):',
    '                      print("zipapp: unexpected member", name)',
    '                      sys.exit(1)',
    '          print("zipapp membership OK:", len(members), "members")',
    '          PY',
    '      - name: Smoke the zipapp',
    '        run: |',
    '          set -euo pipefail',
    '          cd "$RUNNER_TEMP"',
    '          python3 "$RUNNER_TEMP/aos.pyz" --help',
    '          mkdir -p "$RUNNER_TEMP/ws-zipapp"',
    '          python3 "$RUNNER_TEMP/aos.pyz" --root "$RUNNER_TEMP/ws-zipapp" init',
    '          python3 "$RUNNER_TEMP/aos.pyz" --root "$RUNNER_TEMP/ws-zipapp" status',
    '          python3 "$RUNNER_TEMP/aos.pyz" --root "$RUNNER_TEMP/ws-zipapp" doctor',
    '          python3 "$RUNNER_TEMP/aos.pyz" protocol verify-registry',
    '      - name: Assert entrypoint help equivalence',
    '        run: |',
    '          set -euo pipefail',
    '          console_help="$("$RUNNER_TEMP/venv/bin/aos" --help)"',
    '          module_help="$(cd "$GITHUB_WORKSPACE" && python3 -m agentic_os --help)"',
    '          zipapp_help="$(python3 "$RUNNER_TEMP/aos.pyz" --help)"',
    '          test "$console_help" = "$module_help"',
    '          test "$console_help" = "$zipapp_help"',
    '      - name: Clean up bounded build residue',
    '        run: |',
    '          set -euo pipefail',
    '          cd "$GITHUB_WORKSPACE"',
    '          unexpected="$(git status --porcelain --ignored | grep \'^!!\' | grep -vE \'^!! (build/|agentic_os\\.egg-info/)$\' || true)"',
    '          if [ -n "$unexpected" ]; then',
    '            echo "distribution-smoke: unexpected ignored residue present"',
    '            exit 1',
    '          fi',
    '          rm -rf build agentic_os.egg-info',
    '          test ! -e build',
    '          test ! -e agentic_os.egg-info',
    '      - name: Assert a clean working tree',
    '        run: |',
    '          set -euo pipefail',
    '          git diff --exit-code',
    '          test -z "$(git status --porcelain)"',
    '',
)

#: The embedded canonical byte representation. Exact equality with this string
#: is the security boundary; everything below only classifies a rejection.
CANONICAL_TEXT = "\n".join(_CANONICAL_LINES)

DEFAULT_WORKFLOW = ".github/workflows/ci.yml"

# ---------------------------------------------------------------------------
# Frozen facts (contract §5, §7, §8).

#: Immutable two-entry action allowlist: repo -> exact full 40-hex commit SHA.
ACTION_ALLOWLIST = {
    "actions/checkout": "3d3c42e5aac5ba805825da76410c181273ba90b1",
    "actions/setup-python": "5fda3b95a4ea91299a34e894583c3862153e4b97",
}

#: (job id, public check name) pairs — the id/name split of §5.
FROZEN_JOBS = (
    ("workflow-integrity", "workflow-integrity"),
    ("tests-python-3-12", "tests-python-3.12"),
    ("tests-python-3-14", "tests-python-3.14"),
    ("distribution-smoke-python-3-12", "distribution-smoke-python-3.12"),
)
TEST_JOB_IDS = ("tests-python-3-12", "tests-python-3-14")
SMOKE_JOB_ID = "distribution-smoke-python-3-12"
FROZEN_TRIGGERS = ("pull_request", "push", "workflow_dispatch")
FROZEN_PYTHON_LINES = ("3.12", "3.14")

FULL_SUITE_COMMAND = "python3 -m unittest discover -s tests"
REQUIRED_SMOKE_COMMANDS = (
    "python3 -m build --wheel --no-isolation",
    "python3 tools/build_zipapp.py",
    'python3 -m venv "$RUNNER_TEMP/venv"',
    'mkdir -p "$RUNNER_TEMP/ws-wheel"',
    'mkdir -p "$RUNNER_TEMP/ws-zipapp"',
    "rm -rf build agentic_os.egg-info",
    "protocol verify-registry",
)

#: The closed 20-code reason vocabulary (contract §12.2). No code is added,
#: removed, renamed, reordered, or merged without a governed vocabulary change.
REASON_CODES = frozenset({
    "missing_workflow",
    "invalid_utf8",
    "crlf_present",
    "mutable_action_ref",
    "unapproved_action",
    "credential_persistence",
    "write_permission",
    "pull_request_target",
    "secret_reference",
    "continue_on_error",
    "missing_timeout",
    "missing_required_job",
    "missing_required_trigger",
    "missing_python_line",
    "missing_full_suite",
    "missing_distribution_smoke",
    "artifact_upload",
    "shell_download",
    "unexpected_workflow_shape",
    "internal_error",
})

# Regexes below are used ONLY to classify a rejection into a specific reason
# code; they are never the security boundary (that is CANONICAL_TEXT equality).
_OWNER_REPO_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
_WRITE_PERMISSION_RE = re.compile(r"^[a-z][a-z-]*: (?:write|write-all)$")
_SHELL_DOWNLOAD_RE = re.compile(r"\b(?:curl|wget)\b")

_USAGE = (
    "usage: verify_ci_workflow.py [--workflow PATH]\n"
    "Verify a workflow file against the frozen U-P2 canonical grammar."
)


class Finding:
    """One bounded, value-free diagnostic: a reason code and optional locus."""

    __slots__ = ("reason", "locus")

    def __init__(self, reason: str, locus: str | None = None) -> None:
        self.reason = reason
        self.locus = locus

    def key(self):
        return (self.reason, self.locus or "")

    def render(self) -> str:
        if self.locus is None:
            return self.reason
        return f"{self.reason} {self.locus}"


class _UsageError(Exception):
    """A command-line usage error (exit 2), distinct from a workflow finding."""


# ---------------------------------------------------------------------------
# Reading and lightweight structure.

def _read_bytes(path) -> bytes | None:
    try:
        return Path(path).read_bytes()
    except OSError:
        return None


def _job_blocks(lines):
    """Map each 2-space-indented `jobs:` child id to its body lines.

    Lenient by design: correctness rests on CANONICAL_TEXT equality, so this
    only has to attribute lines well enough for the specific-code checks. An
    unexpected shape merely yields imperfect attribution, then the equality
    backstop rejects the file anyway.
    """
    blocks: dict[str, list[str]] = {}
    try:
        start = lines.index("jobs:")
    except ValueError:
        return blocks
    current = None
    body: list[str] = []
    for line in lines[start + 1:]:
        if line.strip() == "":
            if current is not None:
                body.append(line)
            continue
        indent = len(line) - len(line.lstrip(" "))
        if indent == 0:
            break
        stripped = line.strip()
        if indent == 2 and stripped.endswith(":") and not stripped.startswith("-"):
            if current is not None:
                blocks[current] = body
            current = stripped[:-1]
            body = []
        elif current is not None:
            body.append(line)
    if current is not None:
        blocks[current] = body
    return blocks


# ---------------------------------------------------------------------------
# Specific-code classification checks. Each is silent on the canonical file and
# fires only on a deviation that maps to a dedicated reason code.

def _check_actions(lines):
    findings = []
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("uses:"):
            continue
        value = stripped[len("uses:"):].strip()
        parts = value.split()
        token = parts[0] if parts else ""
        if "@" not in token:
            continue  # local action / missing ref -> canonical recognition
        repo, _, ref = token.partition("@")
        if not _OWNER_REPO_RE.match(repo):
            continue  # reusable workflow / local path -> canonical recognition
        locus = f"line:{index + 1}"
        if repo not in ACTION_ALLOWLIST:
            findings.append(Finding("unapproved_action", locus))
        elif ref != ACTION_ALLOWLIST[repo]:
            findings.append(Finding("mutable_action_ref", locus))
    return findings


def _check_artifacts(lines):
    for line in lines:
        if "actions/upload-artifact" in line or "actions/download-artifact" in line:
            return [Finding("artifact_upload")]
    return []


def _check_downloads(lines):
    for line in lines:
        if _SHELL_DOWNLOAD_RE.search(line):
            return [Finding("shell_download")]
    return []


def _check_secrets(lines):
    for line in lines:
        if "secrets." in line:
            return [Finding("secret_reference")]
    return []


def _check_continue_on_error(lines):
    for line in lines:
        if "continue-on-error" in line:
            return [Finding("continue_on_error")]
    return []


def _check_permissions(lines):
    for line in lines:
        if _WRITE_PERMISSION_RE.match(line.strip()):
            return [Finding("write_permission")]
    return []


def _check_credentials(lines):
    findings = []
    for index, line in enumerate(lines):
        if line.strip().startswith("uses: actions/checkout@"):
            window = lines[index + 1:index + 5]
            if not any(w.strip() == "persist-credentials: false" for w in window):
                findings.append(Finding("credential_persistence", f"line:{index + 1}"))
    return findings


def _check_triggers(lines):
    findings = []
    if any("pull_request_target" in line for line in lines):
        findings.append(Finding("pull_request_target"))
    stripped = {line.strip() for line in lines}
    for trigger in FROZEN_TRIGGERS:
        if f"{trigger}:" not in stripped:
            findings.append(Finding("missing_required_trigger", trigger))
    return findings


def _check_jobs(blocks):
    findings = []
    for job_id, job_name in FROZEN_JOBS:
        body = blocks.get(job_id)
        if body is None:
            findings.append(Finding("missing_required_job", job_id))
            continue
        found = None
        for line in body:
            indent = len(line) - len(line.lstrip(" "))
            stripped = line.strip()
            if indent == 4 and stripped.startswith("name:"):
                found = stripped[len("name:"):].strip()
                break
        if found != job_name:
            findings.append(Finding("missing_required_job", job_id))
    return findings


def _check_timeouts(blocks):
    findings = []
    for job_id, _ in FROZEN_JOBS:
        body = blocks.get(job_id)
        if body is None:
            continue  # a missing job is already a missing_required_job
        if not any(line.strip().startswith("timeout-minutes:") for line in body):
            findings.append(Finding("missing_timeout", job_id))
    return findings


def _check_python_lines(lines):
    findings = []
    stripped = {line.strip() for line in lines}
    for feature_line in FROZEN_PYTHON_LINES:
        if f'python-version: "{feature_line}"' not in stripped:
            findings.append(Finding("missing_python_line"))
    return findings


def _check_full_suite(blocks):
    findings = []
    for job_id in TEST_JOB_IDS:
        body = blocks.get(job_id)
        if body is None:
            continue
        if not any(FULL_SUITE_COMMAND in line for line in body):
            findings.append(Finding("missing_full_suite", job_id))
    return findings


def _check_distribution_smoke(lines):
    joined = "\n".join(lines)
    for command in REQUIRED_SMOKE_COMMANDS:
        if command not in joined:
            return [Finding("missing_distribution_smoke", SMOKE_JOB_ID)]
    return []


# ---------------------------------------------------------------------------
# Orchestration.

def _collect_findings(path):
    raw = _read_bytes(path)
    if raw is None:
        return [Finding("missing_workflow")]
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return [Finding("invalid_utf8")]
    if "\r" in text:
        return [Finding("crlf_present")]

    lines = text.split("\n")
    blocks = _job_blocks(lines)

    findings = []
    findings += _check_actions(lines)
    findings += _check_artifacts(lines)
    findings += _check_downloads(lines)
    findings += _check_secrets(lines)
    findings += _check_continue_on_error(lines)
    findings += _check_permissions(lines)
    findings += _check_credentials(lines)
    findings += _check_triggers(lines)
    findings += _check_jobs(blocks)
    findings += _check_timeouts(blocks)
    findings += _check_python_lines(lines)
    findings += _check_full_suite(blocks)
    findings += _check_distribution_smoke(lines)

    # Affirmative recognition backstop: anything not byte-identical to the
    # frozen canonical text that no specific code already named fails closed.
    if not findings and text != CANONICAL_TEXT:
        findings.append(Finding("unexpected_workflow_shape"))
    return findings


def _order(findings):
    ordered = []
    seen = set()
    for finding in sorted(findings, key=lambda f: f.key()):
        key = finding.key()
        if key in seen:
            continue
        seen.add(key)
        ordered.append(finding)
    return ordered


def _parse_args(argv):
    workflow = None
    index = 0
    count = len(argv)
    while index < count:
        arg = argv[index]
        if arg == "--workflow":
            if index + 1 >= count:
                raise _UsageError("--workflow requires a PATH")
            workflow = argv[index + 1]
            index += 2
            continue
        if arg.startswith("--workflow="):
            workflow = arg[len("--workflow="):]
            index += 1
            continue
        raise _UsageError(f"unexpected argument: {arg}")
    return workflow


def _default_path():
    return Path(__file__).resolve().parent.parent / DEFAULT_WORKFLOW


def main(argv=None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    try:
        workflow = _parse_args(list(argv))
    except _UsageError:
        sys.stderr.write(_USAGE + "\n")
        return 2

    path = Path(workflow) if workflow is not None else _default_path()

    # Total top-level guard: any unexpected internal failure becomes exactly one
    # value-free `internal_error` finding and exit 1 — never a traceback, never
    # an output channel for the exception message or file content.
    try:
        findings = _collect_findings(path)
    except Exception:
        findings = [Finding("internal_error")]

    findings = _order(findings)
    if findings:
        sys.stdout.write("".join(f.render() + "\n" for f in findings))
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
