#!/usr/bin/env python3
"""Fail-closed canonical byte-grammar verifier for .github/workflows/ci.yml.

Contract: agentic-os-v0.4-u-p2-delivery-gate-contract.md §12 (D-v0.4.41).

This is deliberately NOT a general YAML parser or an Actions linter, and it does
NOT scan for forbidden substrings. It affirmatively recognizes the ONE frozen
canonical workflow: the security decision is exact equality against an embedded
canonical byte representation (`CANONICAL_TEXT`), so the file is accepted only
when every byte and construct belongs to the single frozen grammar, and any
deviation — an anchor, alias, custom tag, duplicate key, document marker,
multi-document stream, flow-style collection, quoted/escaped key, alternate
boolean spelling, job-level `permissions:` block, local action, reusable
workflow, multiline/folded `uses:`, unexpected block scalar, unknown
job/step/key/ordering, or shell indirection replacing a frozen command — fails
closed. Because the canonical text is clean, the classification checks layered
on top can never cause a false accept: they only *refine* a rejection into the
most specific reason code, defaulting to `unexpected_workflow_shape`. Even if a
classification check had a gap, the equality backstop still rejects.

Standard library only. Opens no socket, spawns no subprocess, mutates nothing,
and stays total: a hostile or corrupt file yields findings, never a traceback.

Interface:

    python3 tools/verify_ci_workflow.py
    python3 tools/verify_ci_workflow.py --workflow .github/workflows/ci.yml

Exit 0 only with zero findings; 1 with findings (one reason code per line on
stdout, deterministically ordered by (reason, locus)); 2 on a usage error.
Diagnostics are value-free and bounded: a reason code from the closed 20-code
vocabulary, optionally followed by a closed-set locus (a frozen job id, a frozen
trigger name, or `line:<n>`). Arbitrary workflow content is never echoed, so a
hostile workflow cannot use the verifier as an output channel.
"""

from __future__ import annotations

import errno
import os
import re
import stat
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Frozen canonical workflow — the embedded authority (contract §6, §10). This
# tuple is generated byte-for-byte from the frozen .github/workflows/ci.yml;
# tests/test_v04_delivery_gate.py::CanonicalAcceptanceTests
# ::test_embedded_canonical_matches_the_real_workflow_file proves it has not
# drifted from the real file.

_CANONICAL_LINES = (
    'name: ci',
    '',
    'on:',
    '  pull_request:',
    '    branches: [main]',
    '  push:',
    '    branches: [main]',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'env:',
    '  PYTHONDONTWRITEBYTECODE: "1"',
    '',
    'defaults:',
    '  run:',
    '    shell: bash',
    '',
    'concurrency:',
    '  group: ci-${{ github.ref }}',
    "  cancel-in-progress: ${{ github.event_name == 'pull_request' }}",
    '',
    'jobs:',
    '  workflow-integrity:',
    '    name: workflow-integrity',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 10',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.12"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Verify workflow integrity',
    '        run: python3 tools/verify_ci_workflow.py',
    '',
    '  tests-python-3-12:',
    '    name: tests-python-3.12',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.12"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Compile all sources',
    '        run: python3 -m compileall -q agentic_os tests tools aos.py aos_hooks.py',
    '      - name: Run the full test suite',
    '        run: python3 -m unittest discover -s tests',
    '      - name: Verify protocol projection',
    '        run: python3 tools/gen_protocols.py',
    '      - name: Assert a clean working tree',
    '        run: |',
    '          set -euo pipefail',
    '          git diff --exit-code',
    '          status="$(git status --porcelain)"',
    '          test -z "$status"',
    '',
    '  tests-python-3-14:',
    '    name: tests-python-3.14',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.14"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Compile all sources',
    '        run: python3 -m compileall -q agentic_os tests tools aos.py aos_hooks.py',
    '      - name: Run the full test suite',
    '        run: python3 -m unittest discover -s tests',
    '      - name: Verify protocol projection',
    '        run: python3 tools/gen_protocols.py',
    '      - name: Assert a clean working tree',
    '        run: |',
    '          set -euo pipefail',
    '          git diff --exit-code',
    '          status="$(git status --porcelain)"',
    '          test -z "$status"',
    '',
    '  distribution-smoke-python-3-12:',
    '    name: distribution-smoke-python-3.12',
    '    runs-on: ubuntu-24.04',
    '    timeout-minutes: 30',
    '    steps:',
    '      - name: Check out repository',
    '        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1        # v7.0.1',
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Python',
    '        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0',
    '        with:',
    '          python-version: "3.12"',
    '      - name: Print interpreter and platform',
    '        run: python3 -VV && python3 -m pip --version && uname -a',
    '      - name: Install pinned build tools',
    '        run: |',
    '          set -euo pipefail',
    '          python3 -m pip install pip==26.1.2',
    '          python3 -m pip install build==1.5.0 setuptools==83.0.0 packaging==26.2 pyproject_hooks==1.2.0',
    '          python3 -m pip freeze',
    '      - name: Build the wheel',
    '        run: python3 -m build --wheel --no-isolation --outdir "$RUNNER_TEMP/dist"',
    '      - name: Assert wheel membership',
    '        run: |',
    '          set -euo pipefail',
    "          python3 - <<'PY'",
    '          import glob, os, re, sys, zipfile',
    '          def fail(message):',
    '              print("wheel: " + message)',
    '              sys.exit(1)',
    '          runner_temp = os.environ["RUNNER_TEMP"]',
    '          wheels = sorted(glob.glob(os.path.join(runner_temp, "dist", "agentic_os-*.whl")))',
    '          if len(wheels) != 1:',
    '              fail("expected exactly one wheel, found " + str(len(wheels)))',
    '          source_py = {}',
    '          for path in glob.glob("agentic_os/**/*.py", recursive=True):',
    '              if "__pycache__" in path.split(os.sep):',
    '                  continue',
    '              with open(path, "rb") as handle:',
    '                  source_py[path.replace(os.sep, "/")] = handle.read()',
    '          if not source_py:',
    '              fail("no source package modules found")',
    '          source_catalog = {}',
    '          for path in sorted(glob.glob(os.path.join("agentic_os", "catalog", "*.json"))):',
    '              with open(path, "rb") as handle:',
    '                  source_catalog[path.replace(os.sep, "/")] = handle.read()',
    '          if len(source_catalog) != 13:',
    '              fail("expected 13 source catalog json files, found " + str(len(source_catalog)))',
    '          dist_info_member = re.compile(r"^(agentic_os-[^/]+\\.dist-info)/[^/]+$")',
    '          dist_info_root = re.compile(r"^agentic_os-[^/]+\\.dist-info$")',
    '          def unsafe(name):',
    '              bare = name[:-1] if name.endswith("/") else name',
    '              if not bare or "\\x00" in name or "\\\\" in name or name.startswith("/"):',
    '                  return True',
    '              if len(name) > 1 and name[0].isascii() and name[0].isalpha() and name[1] == ":":',
    '                  return True',
    '              return any(part in ("", ".", "..") for part in bare.split("/"))',
    '          seen = set()',
    '          seen_folded = set()',
    '          wheel_py = {}',
    '          wheel_catalog = {}',
    '          dist_info_roots = set()',
    '          with zipfile.ZipFile(wheels[0]) as archive:',
    '              for name in archive.namelist():',
    '                  if unsafe(name):',
    '                      fail("unsafe member path")',
    '                  if name in seen:',
    '                      fail("duplicate member")',
    '                  seen.add(name)',
    '                  folded = name.lower()',
    '                  if folded in seen_folded:',
    '                      fail("case-folded duplicate member")',
    '                  seen_folded.add(folded)',
    '                  if name.endswith("/"):',
    '                      top = name.split("/", 1)[0]',
    '                      if top != "agentic_os" and not dist_info_root.match(top):',
    '                          fail("unexpected directory entry")',
    '                      continue',
    '                  if name in source_py:',
    '                      wheel_py[name] = archive.read(name)',
    '                  elif name in source_catalog:',
    '                      wheel_catalog[name] = archive.read(name)',
    '                  else:',
    '                      match = dist_info_member.match(name)',
    '                      if not match:',
    '                          fail("unexpected member")',
    '                      dist_info_roots.add(match.group(1))',
    '          if wheel_py.keys() != source_py.keys():',
    '              fail("package modules do not match the source tree")',
    '          for name, data in source_py.items():',
    '              if wheel_py[name] != data:',
    '                  fail("package module bytes differ from the source tree")',
    '          if wheel_catalog.keys() != source_catalog.keys():',
    '              fail("catalog json set does not match the source tree")',
    '          for name, data in source_catalog.items():',
    '              if wheel_catalog[name] != data:',
    '                  fail("catalog json bytes differ from the source tree")',
    '          if len(dist_info_roots) != 1:',
    '              fail("expected exactly one dist-info root, found " + str(len(dist_info_roots)))',
    '          print("wheel membership OK: " + str(len(seen)) + " members")',
    '          PY',
    '      - name: Install the wheel and smoke the console script',
    '        run: |',
    '          set -euo pipefail',
    '          unset PYTHONPATH',
    '          python3 -m venv "$RUNNER_TEMP/venv"',
    '          "$RUNNER_TEMP/venv/bin/python" -m pip install --no-deps "$RUNNER_TEMP"/dist/agentic_os-*.whl',
    '          cd "$RUNNER_TEMP"',
    '          "$RUNNER_TEMP/venv/bin/aos" --help',
    '          mkdir -p "$RUNNER_TEMP/ws-wheel"',
    '          "$RUNNER_TEMP/venv/bin/aos" --root "$RUNNER_TEMP/ws-wheel" init',
    '          "$RUNNER_TEMP/venv/bin/aos" --root "$RUNNER_TEMP/ws-wheel" status',
    '          "$RUNNER_TEMP/venv/bin/aos" --root "$RUNNER_TEMP/ws-wheel" doctor',
    '          "$RUNNER_TEMP/venv/bin/aos" protocol verify-registry',
    '      - name: Build the zipapp',
    '        run: python3 tools/build_zipapp.py --output "$RUNNER_TEMP/aos.pyz"',
    '      - name: Assert zipapp membership',
    '        run: |',
    '          set -euo pipefail',
    "          python3 - <<'PY'",
    '          import glob, os, sys, zipfile',
    '          def fail(message):',
    '              print("zipapp: " + message)',
    '              sys.exit(1)',
    '          runner_temp = os.environ["RUNNER_TEMP"]',
    '          expected = {}',
    '          with open(os.path.join("agentic_os", "__main__.py"), "rb") as handle:',
    '              expected["__main__.py"] = handle.read()',
    '          for path in glob.glob("agentic_os/**/*.py", recursive=True):',
    '              if "__pycache__" in path.split(os.sep):',
    '                  continue',
    '              with open(path, "rb") as handle:',
    '                  expected[path.replace(os.sep, "/")] = handle.read()',
    '          for path in sorted(glob.glob(os.path.join("agentic_os", "catalog", "*.json"))):',
    '              with open(path, "rb") as handle:',
    '                  expected[path.replace(os.sep, "/")] = handle.read()',
    '          def unsafe(name):',
    '              bare = name[:-1] if name.endswith("/") else name',
    '              if not bare or "\\x00" in name or "\\\\" in name or name.startswith("/"):',
    '                  return True',
    '              if len(name) > 1 and name[0].isascii() and name[0].isalpha() and name[1] == ":":',
    '                  return True',
    '              return any(part in ("", ".", "..") for part in bare.split("/"))',
    '          seen = set()',
    '          seen_folded = set()',
    '          payload = {}',
    '          with zipfile.ZipFile(os.path.join(runner_temp, "aos.pyz")) as archive:',
    '              for name in archive.namelist():',
    '                  if unsafe(name):',
    '                      fail("unsafe member path")',
    '                  if name in seen:',
    '                      fail("duplicate member")',
    '                  seen.add(name)',
    '                  folded = name.lower()',
    '                  if folded in seen_folded:',
    '                      fail("case-folded duplicate member")',
    '                  seen_folded.add(folded)',
    '                  if name.endswith("/"):',
    '                      if name.split("/", 1)[0] != "agentic_os":',
    '                          fail("unexpected directory entry")',
    '                      continue',
    '                  if name not in expected:',
    '                      fail("unexpected member")',
    '                  payload[name] = archive.read(name)',
    '          if payload.keys() != expected.keys():',
    '              fail("archive members do not match the source tree")',
    '          for name, data in expected.items():',
    '              if payload[name] != data:',
    '                  fail("archive member bytes differ from the source tree")',
    '          print("zipapp membership OK: " + str(len(seen)) + " members")',
    '          PY',
    '      - name: Smoke the zipapp',
    '        run: |',
    '          set -euo pipefail',
    '          unset PYTHONPATH',
    '          cd "$RUNNER_TEMP"',
    '          python3 "$RUNNER_TEMP/aos.pyz" --help',
    '          mkdir -p "$RUNNER_TEMP/ws-zipapp"',
    '          python3 "$RUNNER_TEMP/aos.pyz" --root "$RUNNER_TEMP/ws-zipapp" init',
    '          python3 "$RUNNER_TEMP/aos.pyz" --root "$RUNNER_TEMP/ws-zipapp" status',
    '          python3 "$RUNNER_TEMP/aos.pyz" --root "$RUNNER_TEMP/ws-zipapp" doctor',
    '          python3 "$RUNNER_TEMP/aos.pyz" protocol verify-registry',
    '      - name: Assert entrypoint help equivalence',
    '        run: |',
    '          set -euo pipefail',
    '          unset PYTHONPATH',
    '          console_help="$("$RUNNER_TEMP/venv/bin/aos" --help)"',
    '          module_help="$(cd "$GITHUB_WORKSPACE" && python3 -m agentic_os --help)"',
    '          zipapp_help="$(python3 "$RUNNER_TEMP/aos.pyz" --help)"',
    '          test "$console_help" = "$module_help"',
    '          test "$console_help" = "$zipapp_help"',
    '      - name: Clean up bounded build residue',
    '        run: |',
    '          set -euo pipefail',
    '          cd "$GITHUB_WORKSPACE"',
    '          ignored_residue="$(git status --porcelain --ignored)"',
    '          unexpected="$(grep \'^!!\' <<<"$ignored_residue" | grep -vE \'^!! (build/|agentic_os\\.egg-info/)$\' || true)"',
    '          if [ -n "$unexpected" ]; then',
    '            echo "distribution-smoke: unexpected ignored residue present"',
    '            exit 1',
    '          fi',
    '          rm -rf build agentic_os.egg-info',
    '          test ! -e build',
    '          test ! -e agentic_os.egg-info',
    '      - name: Assert a clean working tree',
    '        run: |',
    '          set -euo pipefail',
    '          git diff --exit-code',
    '          status="$(git status --porcelain)"',
    '          test -z "$status"',
    '',
)

#: The embedded canonical byte representation. Exact equality with this string
#: is the security boundary; everything below only classifies a rejection.
CANONICAL_TEXT = "\n".join(_CANONICAL_LINES)

DEFAULT_WORKFLOW = ".github/workflows/ci.yml"

# ---------------------------------------------------------------------------
# Frozen facts (contract §5, §7, §8).

#: Immutable two-entry action allowlist: repo -> exact full 40-hex commit SHA.
ACTION_ALLOWLIST = {
    "actions/checkout": "3d3c42e5aac5ba805825da76410c181273ba90b1",
    "actions/setup-python": "5fda3b95a4ea91299a34e894583c3862153e4b97",
}

#: (job id, public check name) pairs — the id/name split of §5.
FROZEN_JOBS = (
    ("workflow-integrity", "workflow-integrity"),
    ("tests-python-3-12", "tests-python-3.12"),
    ("tests-python-3-14", "tests-python-3.14"),
    ("distribution-smoke-python-3-12", "distribution-smoke-python-3.12"),
)
TEST_JOB_IDS = ("tests-python-3-12", "tests-python-3-14")
SMOKE_JOB_ID = "distribution-smoke-python-3-12"
FROZEN_TRIGGERS = ("pull_request", "push", "workflow_dispatch")
FROZEN_PYTHON_LINES = ("3.12", "3.14")

FULL_SUITE_COMMAND = "python3 -m unittest discover -s tests"
REQUIRED_SMOKE_COMMANDS = (
    "python3 -m build --wheel --no-isolation",
    "python3 tools/build_zipapp.py",
    'python3 -m venv "$RUNNER_TEMP/venv"',
    'mkdir -p "$RUNNER_TEMP/ws-wheel"',
    'mkdir -p "$RUNNER_TEMP/ws-zipapp"',
    "rm -rf build agentic_os.egg-info",
    "protocol verify-registry",
)

#: The closed 20-code reason vocabulary (contract §12.2). No code is added,
#: removed, renamed, reordered, or merged without a governed vocabulary change.
REASON_CODES = frozenset({
    "missing_workflow",
    "invalid_utf8",
    "crlf_present",
    "mutable_action_ref",
    "unapproved_action",
    "credential_persistence",
    "write_permission",
    "pull_request_target",
    "secret_reference",
    "continue_on_error",
    "missing_timeout",
    "missing_required_job",
    "missing_required_trigger",
    "missing_python_line",
    "missing_full_suite",
    "missing_distribution_smoke",
    "artifact_upload",
    "shell_download",
    "unexpected_workflow_shape",
    "internal_error",
})

# Regexes below are used ONLY to classify a rejection into a specific reason
# code; they are never the security boundary (that is CANONICAL_TEXT equality).
_OWNER_REPO_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
_WRITE_PERMISSION_RE = re.compile(r"^[a-z][a-z-]*: (?:write|write-all)$")
_SHELL_DOWNLOAD_RE = re.compile(r"\b(?:curl|wget)\b")

_USAGE = (
    "usage: verify_ci_workflow.py [--workflow PATH]\n"
    "Verify a workflow file against the frozen U-P2 canonical grammar."
)


class Finding:
    """One bounded, value-free diagnostic: a reason code and optional locus."""

    __slots__ = ("reason", "locus")

    def __init__(self, reason: str, locus: str | None = None) -> None:
        self.reason = reason
        self.locus = locus

    def key(self):
        return (self.reason, self.locus or "")

    def render(self) -> str:
        if self.locus is None:
            return self.reason
        return f"{self.reason} {self.locus}"


class _UsageError(Exception):
    """A command-line usage error (exit 2), distinct from a workflow finding."""


# ---------------------------------------------------------------------------
# Reading and lightweight structure.

#: A deterministic upper bound on the workflow file, comfortably above the
#: canonical size (~13 KiB). A regular file larger than this is refused before
#: any content is decoded, so a hostile or corrupt target cannot force an
#: unbounded read or allocation.
MAX_WORKFLOW_BYTES = 1 << 20  # 1 MiB


class _ReadResult:
    """Outcome of reading the workflow target: bytes on success, else a reason.

    `reason`, when set, is an existing closed reason code — `missing_workflow`
    for an absent or unopenable target, `unexpected_workflow_shape` for a
    non-regular (directory, FIFO, device, socket, symlink) or oversized target.
    No new reason code is introduced.
    """

    __slots__ = ("data", "reason")

    def __init__(self, data: bytes | None = None, reason: str | None = None) -> None:
        self.data = data
        self.reason = reason


def _read_bytes(path) -> _ReadResult:
    """Bounded, symlink-refusing read of a single regular file.

    Opens the target with O_NOFOLLOW (never follow a final-component symlink)
    and O_NONBLOCK (never block on a FIFO with no writer) where the platform
    provides them, confirms via fstat on the descriptor that it is a regular
    file no larger than MAX_WORKFLOW_BYTES, then reads at most that bound plus
    one byte — a file that grew after fstat is refused rather than silently
    truncated into a spurious accept. The descriptor is always closed. On a
    platform without O_NOFOLLOW the open cannot refuse a final-component symlink
    at the syscall level; the byte-equality backstop still fails closed there,
    since only exactly-canonical bytes are ever accepted however they arrive.
    """
    flags = os.O_RDONLY
    flags |= getattr(os, "O_NONBLOCK", 0)
    flags |= getattr(os, "O_NOFOLLOW", 0)
    flags |= getattr(os, "O_CLOEXEC", 0)
    try:
        fd = os.open(os.fspath(path), flags)
    except FileNotFoundError:
        return _ReadResult(reason="missing_workflow")
    except OSError as exc:
        if exc.errno == errno.ELOOP:  # a symlink refused by O_NOFOLLOW
            return _ReadResult(reason="unexpected_workflow_shape")
        return _ReadResult(reason="missing_workflow")  # unopenable target
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode):
            return _ReadResult(reason="unexpected_workflow_shape")
        if info.st_size > MAX_WORKFLOW_BYTES:
            return _ReadResult(reason="unexpected_workflow_shape")
        chunks: list[bytes] = []
        remaining = MAX_WORKFLOW_BYTES + 1
        while remaining > 0:
            try:
                chunk = os.read(fd, min(65536, remaining))
            except BlockingIOError:  # a nonblocking pipe with no data ready
                return _ReadResult(reason="unexpected_workflow_shape")
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        data = b"".join(chunks)
        if len(data) > MAX_WORKFLOW_BYTES:
            return _ReadResult(reason="unexpected_workflow_shape")
        return _ReadResult(data=data)
    finally:
        os.close(fd)


def _job_blocks(lines):
    """Map each 2-space-indented `jobs:` child id to its body lines.

    Lenient by design: correctness rests on CANONICAL_TEXT equality, so this
    only has to attribute lines well enough for the specific-code checks. An
    unexpected shape merely yields imperfect attribution, then the equality
    backstop rejects the file anyway.
    """
    blocks: dict[str, list[str]] = {}
    try:
        start = lines.index("jobs:")
    except ValueError:
        return blocks
    current = None
    body: list[str] = []
    for line in lines[start + 1:]:
        if line.strip() == "":
            if current is not None:
                body.append(line)
            continue
        indent = len(line) - len(line.lstrip(" "))
        if indent == 0:
            break
        stripped = line.strip()
        if indent == 2 and stripped.endswith(":") and not stripped.startswith("-"):
            if current is not None:
                blocks[current] = body
            current = stripped[:-1]
            body = []
        elif current is not None:
            body.append(line)
    if current is not None:
        blocks[current] = body
    return blocks


# ---------------------------------------------------------------------------
# Specific-code classification checks. Each is silent on the canonical file and
# fires only on a deviation that maps to a dedicated reason code.

def _check_actions(lines):
    findings = []
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("uses:"):
            continue
        value = stripped[len("uses:"):].strip()
        parts = value.split()
        token = parts[0] if parts else ""
        if "@" not in token:
            continue  # local action / missing ref -> canonical recognition
        repo, _, ref = token.partition("@")
        if not _OWNER_REPO_RE.match(repo):
            continue  # reusable workflow / local path -> canonical recognition
        locus = f"line:{index + 1}"
        if repo not in ACTION_ALLOWLIST:
            findings.append(Finding("unapproved_action", locus))
        elif ref != ACTION_ALLOWLIST[repo]:
            findings.append(Finding("mutable_action_ref", locus))
    return findings


def _check_artifacts(lines):
    for line in lines:
        if "actions/upload-artifact" in line or "actions/download-artifact" in line:
            return [Finding("artifact_upload")]
    return []


def _check_downloads(lines):
    for line in lines:
        if _SHELL_DOWNLOAD_RE.search(line):
            return [Finding("shell_download")]
    return []


def _check_secrets(lines):
    for line in lines:
        if "secrets." in line:
            return [Finding("secret_reference")]
    return []


def _check_continue_on_error(lines):
    for line in lines:
        if "continue-on-error" in line:
            return [Finding("continue_on_error")]
    return []


def _check_permissions(lines):
    for line in lines:
        if _WRITE_PERMISSION_RE.match(line.strip()):
            return [Finding("write_permission")]
    return []


def _check_credentials(lines):
    findings = []
    for index, line in enumerate(lines):
        if line.strip().startswith("uses: actions/checkout@"):
            window = lines[index + 1:index + 5]
            if not any(w.strip() == "persist-credentials: false" for w in window):
                findings.append(Finding("credential_persistence", f"line:{index + 1}"))
    return findings


def _check_triggers(lines):
    findings = []
    if any("pull_request_target" in line for line in lines):
        findings.append(Finding("pull_request_target"))
    stripped = {line.strip() for line in lines}
    for trigger in FROZEN_TRIGGERS:
        if f"{trigger}:" not in stripped:
            findings.append(Finding("missing_required_trigger", trigger))
    return findings


def _check_jobs(blocks):
    findings = []
    for job_id, job_name in FROZEN_JOBS:
        body = blocks.get(job_id)
        if body is None:
            findings.append(Finding("missing_required_job", job_id))
            continue
        found = None
        for line in body:
            indent = len(line) - len(line.lstrip(" "))
            stripped = line.strip()
            if indent == 4 and stripped.startswith("name:"):
                found = stripped[len("name:"):].strip()
                break
        if found != job_name:
            findings.append(Finding("missing_required_job", job_id))
    return findings


def _check_timeouts(blocks):
    findings = []
    for job_id, _ in FROZEN_JOBS:
        body = blocks.get(job_id)
        if body is None:
            continue  # a missing job is already a missing_required_job
        if not any(line.strip().startswith("timeout-minutes:") for line in body):
            findings.append(Finding("missing_timeout", job_id))
    return findings


def _check_python_lines(lines):
    findings = []
    stripped = {line.strip() for line in lines}
    for feature_line in FROZEN_PYTHON_LINES:
        if f'python-version: "{feature_line}"' not in stripped:
            findings.append(Finding("missing_python_line"))
    return findings


def _check_full_suite(blocks):
    findings = []
    for job_id in TEST_JOB_IDS:
        body = blocks.get(job_id)
        if body is None:
            continue
        if not any(FULL_SUITE_COMMAND in line for line in body):
            findings.append(Finding("missing_full_suite", job_id))
    return findings


def _check_distribution_smoke(lines):
    joined = "\n".join(lines)
    for command in REQUIRED_SMOKE_COMMANDS:
        if command not in joined:
            return [Finding("missing_distribution_smoke", SMOKE_JOB_ID)]
    return []


# ---------------------------------------------------------------------------
# Orchestration.

def _collect_findings(path):
    result = _read_bytes(path)
    if result.data is None:
        return [Finding(result.reason or "missing_workflow")]
    raw = result.data
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return [Finding("invalid_utf8")]
    if "\r" in text:
        return [Finding("crlf_present")]

    lines = text.split("\n")
    blocks = _job_blocks(lines)

    findings = []
    findings += _check_actions(lines)
    findings += _check_artifacts(lines)
    findings += _check_downloads(lines)
    findings += _check_secrets(lines)
    findings += _check_continue_on_error(lines)
    findings += _check_permissions(lines)
    findings += _check_credentials(lines)
    findings += _check_triggers(lines)
    findings += _check_jobs(blocks)
    findings += _check_timeouts(blocks)
    findings += _check_python_lines(lines)
    findings += _check_full_suite(blocks)
    findings += _check_distribution_smoke(lines)

    # Affirmative recognition backstop: anything not byte-identical to the
    # frozen canonical text that no specific code already named fails closed.
    if not findings and text != CANONICAL_TEXT:
        findings.append(Finding("unexpected_workflow_shape"))
    return findings


def _order(findings):
    ordered = []
    seen = set()
    for finding in sorted(findings, key=lambda f: f.key()):
        key = finding.key()
        if key in seen:
            continue
        seen.add(key)
        ordered.append(finding)
    return ordered


def _parse_args(argv):
    workflow = None
    index = 0
    count = len(argv)
    while index < count:
        arg = argv[index]
        if arg == "--workflow":
            if index + 1 >= count:
                raise _UsageError("--workflow requires a PATH")
            workflow = argv[index + 1]
            index += 2
            continue
        if arg.startswith("--workflow="):
            workflow = arg[len("--workflow="):]
            index += 1
            continue
        raise _UsageError(f"unexpected argument: {arg}")
    return workflow


def _default_path():
    return Path(__file__).resolve().parent.parent / DEFAULT_WORKFLOW


def main(argv=None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    try:
        workflow = _parse_args(list(argv))
    except _UsageError:
        sys.stderr.write(_USAGE + "\n")
        return 2

    path = Path(workflow) if workflow is not None else _default_path()

    # Total top-level guard: any unexpected internal failure becomes exactly one
    # value-free `internal_error` finding and exit 1 — never a traceback, never
    # an output channel for the exception message or file content.
    try:
        findings = _collect_findings(path)
    except Exception:
        findings = [Finding("internal_error")]

    findings = _order(findings)
    if findings:
        sys.stdout.write("".join(f.render() + "\n" for f in findings))
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
